package xtra

const ptx75 = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-26907403
// Cuda compilation tools, release 10.1, V10.1.243
// Based on LLVM 3.4svn
//

.version 6.4
.target sm_75
.address_size 64

	// .globl	Transpose

.visible .entry Transpose(
	.param .u32 Transpose_param_0,
	.param .u64 Transpose_param_1,
	.param .u64 Transpose_param_2,
	.param .u32 Transpose_param_3,
	.param .u64 Transpose_param_4
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<105>;
	.reg .b64 	%rd<45>;


	ld.param.u32 	%r32, [Transpose_param_0];
	ld.param.u64 	%rd11, [Transpose_param_1];
	ld.param.u64 	%rd13, [Transpose_param_2];
	ld.param.u32 	%r33, [Transpose_param_3];
	ld.param.u64 	%rd12, [Transpose_param_4];
	cvta.to.global.u64 	%rd1, %rd13;
	shl.b32 	%r1, %r33, 1;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r34, %ctaid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r91, %r2, %r34, %r35;
	setp.ge.s32	%p1, %r91, %r32;
	@%p1 bra 	BB0_15;

	cvta.to.global.u64 	%rd2, %rd12;
	cvta.to.global.u64 	%rd3, %rd11;
	mov.u32 	%r36, %nctaid.x;
	mul.lo.s32 	%r4, %r36, %r2;
	and.b32  	%r5, %r33, 3;
	mul.wide.s32 	%rd7, %r33, 4;
	add.s64 	%rd4, %rd1, %rd7;
	mul.wide.s32 	%rd14, %r1, 4;
	add.s64 	%rd5, %rd1, %rd14;

BB0_2:
	mov.u32 	%r104, 0;
	setp.lt.s32	%p2, %r33, 1;
	@%p2 bra 	BB0_14;

	mov.u32 	%r98, 0;
	setp.eq.s32	%p3, %r5, 0;
	@%p3 bra 	BB0_4;

	setp.eq.s32	%p4, %r5, 1;
	@%p4 bra 	BB0_6;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r96, %r91;
	mov.u32 	%r97, %r98;
	bra.uni 	BB0_10;

BB0_4:
	mov.u32 	%r99, %r91;
	mov.u32 	%r104, %r98;
	bra.uni 	BB0_11;

BB0_7:
	setp.eq.s32	%p5, %r5, 2;
	mov.u32 	%r93, %r91;
	mov.u32 	%r94, %r98;
	@%p5 bra 	BB0_9;

	ld.global.u32 	%r46, [%rd4];
	div.s32 	%r47, %r91, %r46;
	mul.lo.s32 	%r48, %r47, %r46;
	sub.s32 	%r93, %r91, %r48;
	ld.global.u32 	%r49, [%rd5];
	mul.wide.s32 	%rd15, %r49, 4;
	add.s64 	%rd16, %rd1, %rd15;
	ld.global.u32 	%r50, [%rd16];
	mul.lo.s32 	%r94, %r50, %r47;
	mov.u32 	%r98, 1;

BB0_9:
	add.s32 	%r51, %r98, %r33;
	mul.wide.s32 	%rd17, %r51, 4;
	add.s64 	%rd18, %rd1, %rd17;
	ld.global.u32 	%r52, [%rd18];
	div.s32 	%r53, %r93, %r52;
	mul.lo.s32 	%r54, %r53, %r52;
	sub.s32 	%r96, %r93, %r54;
	add.s32 	%r55, %r98, %r1;
	mul.wide.s32 	%rd19, %r55, 4;
	add.s64 	%rd20, %rd1, %rd19;
	ld.global.u32 	%r56, [%rd20];
	mul.wide.s32 	%rd21, %r56, 4;
	add.s64 	%rd22, %rd1, %rd21;
	ld.global.u32 	%r57, [%rd22];
	mad.lo.s32 	%r97, %r57, %r53, %r94;
	add.s32 	%r98, %r98, 1;

BB0_10:
	add.s32 	%r58, %r98, %r33;
	mul.wide.s32 	%rd23, %r58, 4;
	add.s64 	%rd24, %rd1, %rd23;
	ld.global.u32 	%r59, [%rd24];
	div.s32 	%r60, %r96, %r59;
	mul.lo.s32 	%r61, %r60, %r59;
	sub.s32 	%r99, %r96, %r61;
	add.s32 	%r62, %r98, %r1;
	mul.wide.s32 	%rd25, %r62, 4;
	add.s64 	%rd26, %rd1, %rd25;
	ld.global.u32 	%r63, [%rd26];
	mul.wide.s32 	%rd27, %r63, 4;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.u32 	%r64, [%rd28];
	mad.lo.s32 	%r104, %r64, %r60, %r97;
	add.s32 	%r98, %r98, 1;

BB0_11:
	setp.lt.u32	%p6, %r33, 4;
	@%p6 bra 	BB0_14;

	mul.wide.s32 	%rd29, %r98, 4;
	add.s64 	%rd44, %rd1, %rd29;

BB0_13:
	add.s64 	%rd30, %rd44, %rd7;
	ld.global.u32 	%r65, [%rd30];
	div.s32 	%r66, %r99, %r65;
	mul.lo.s32 	%r67, %r66, %r65;
	sub.s32 	%r68, %r99, %r67;
	add.s64 	%rd31, %rd44, %rd14;
	ld.global.u32 	%r69, [%rd31];
	mul.wide.s32 	%rd32, %r69, 4;
	add.s64 	%rd33, %rd1, %rd32;
	ld.global.u32 	%r70, [%rd33];
	mad.lo.s32 	%r71, %r70, %r66, %r104;
	ld.global.u32 	%r72, [%rd30+4];
	div.s32 	%r73, %r68, %r72;
	mul.lo.s32 	%r74, %r73, %r72;
	sub.s32 	%r75, %r68, %r74;
	ld.global.u32 	%r76, [%rd31+4];
	mul.wide.s32 	%rd34, %r76, 4;
	add.s64 	%rd35, %rd1, %rd34;
	ld.global.u32 	%r77, [%rd35];
	mad.lo.s32 	%r78, %r77, %r73, %r71;
	ld.global.u32 	%r79, [%rd30+8];
	div.s32 	%r80, %r75, %r79;
	mul.lo.s32 	%r81, %r80, %r79;
	sub.s32 	%r82, %r75, %r81;
	ld.global.u32 	%r83, [%rd31+8];
	mul.wide.s32 	%rd36, %r83, 4;
	add.s64 	%rd37, %rd1, %rd36;
	ld.global.u32 	%r84, [%rd37];
	mad.lo.s32 	%r85, %r84, %r80, %r78;
	ld.global.u32 	%r86, [%rd30+12];
	div.s32 	%r87, %r82, %r86;
	mul.lo.s32 	%r88, %r87, %r86;
	sub.s32 	%r99, %r82, %r88;
	ld.global.u32 	%r89, [%rd31+12];
	mul.wide.s32 	%rd38, %r89, 4;
	add.s64 	%rd39, %rd1, %rd38;
	ld.global.u32 	%r90, [%rd39];
	mad.lo.s32 	%r104, %r90, %r87, %r85;
	add.s64 	%rd44, %rd44, 16;
	add.s32 	%r98, %r98, 4;
	setp.lt.s32	%p7, %r98, %r33;
	@%p7 bra 	BB0_13;

BB0_14:
	mul.wide.s32 	%rd40, %r104, 4;
	add.s64 	%rd41, %rd3, %rd40;
	ld.global.f32 	%f1, [%rd41];
	mul.wide.s32 	%rd42, %r91, 4;
	add.s64 	%rd43, %rd2, %rd42;
	st.global.f32 	[%rd43], %f1;
	add.s32 	%r91, %r4, %r91;
	setp.lt.s32	%p8, %r91, %r32;
	@%p8 bra 	BB0_2;

BB0_15:
	ret;
}

	// .globl	SwapEveryOther
.visible .entry SwapEveryOther(
	.param .u32 SwapEveryOther_param_0,
	.param .u32 SwapEveryOther_param_1,
	.param .u64 SwapEveryOther_param_2,
	.param .u64 SwapEveryOther_param_3,
	.param .u32 SwapEveryOther_param_4,
	.param .u32 SwapEveryOther_param_5
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<8>;


	ld.param.u32 	%r8, [SwapEveryOther_param_0];
	ld.param.u32 	%r9, [SwapEveryOther_param_1];
	ld.param.u64 	%rd3, [SwapEveryOther_param_2];
	ld.param.u64 	%rd4, [SwapEveryOther_param_3];
	ld.param.u32 	%r17, [SwapEveryOther_param_4];
	ld.param.u32 	%r11, [SwapEveryOther_param_5];
	setp.ge.s32	%p1, %r17, %r9;
	@%p1 bra 	BB1_6;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd3;
	mov.u32 	%r12, %ctaid.x;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r1, %r13, %r12, %r14;
	mov.u32 	%r15, %nctaid.x;
	mul.lo.s32 	%r2, %r15, %r13;

BB1_2:
	setp.ge.s32	%p2, %r1, %r8;
	@%p2 bra 	BB1_5;

	mul.lo.s32 	%r4, %r17, %r8;
	mov.u32 	%r18, %r1;

BB1_4:
	add.s32 	%r16, %r18, %r4;
	mul.wide.s32 	%rd5, %r16, 4;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f1, [%rd6];
	add.s64 	%rd7, %rd1, %rd5;
	ld.global.f32 	%f2, [%rd7];
	st.global.f32 	[%rd6], %f2;
	st.global.f32 	[%rd7], %f1;
	add.s32 	%r18, %r2, %r18;
	setp.lt.s32	%p3, %r18, %r8;
	@%p3 bra 	BB1_4;

BB1_5:
	bar.sync 	0;
	add.s32 	%r17, %r17, %r11;
	setp.lt.s32	%p4, %r17, %r9;
	@%p4 bra 	BB1_2;

BB1_6:
	ret;
}

	// .globl	SwapUpperLower
.visible .entry SwapUpperLower(
	.param .u32 SwapUpperLower_param_0,
	.param .u32 SwapUpperLower_param_1,
	.param .u64 SwapUpperLower_param_2,
	.param .u64 SwapUpperLower_param_3,
	.param .u32 SwapUpperLower_param_4,
	.param .u32 SwapUpperLower_param_5,
	.param .u32 SwapUpperLower_param_6
)
{
	.reg .pred 	%p<18>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<15>;


	ld.param.u32 	%r26, [SwapUpperLower_param_1];
	ld.param.u64 	%rd3, [SwapUpperLower_param_2];
	ld.param.u64 	%rd4, [SwapUpperLower_param_3];
	ld.param.u32 	%r28, [SwapUpperLower_param_4];
	ld.param.u32 	%r27, [SwapUpperLower_param_5];
	ld.param.u32 	%r25, [SwapUpperLower_param_0];
	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd3;
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r29, %ctaid.x;
	mov.u32 	%r30, %tid.x;
	mad.lo.s32 	%r48, %r1, %r29, %r30;
	shr.u32 	%r31, %r25, 31;
	add.s32 	%r32, %r25, %r31;
	shr.s32 	%r3, %r32, 1;
	setp.gt.s32	%p1, %r28, 0;
	@%p1 bra 	BB2_7;
	bra.uni 	BB2_1;

BB2_7:
	setp.ge.s32	%p9, %r48, %r3;
	@%p9 bra 	BB2_13;

	setp.gt.s32	%p10, %r27, 0;
	selp.b32	%r14, 0, %r3, %p10;
	mov.u32 	%r41, %ntid.y;
	mov.u32 	%r42, %ctaid.y;
	mov.u32 	%r43, %tid.y;
	mad.lo.s32 	%r15, %r41, %r42, %r43;
	mov.u32 	%r44, %nctaid.y;
	mul.lo.s32 	%r16, %r44, %r41;
	mov.u32 	%r45, %nctaid.x;
	mul.lo.s32 	%r17, %r45, %r1;

BB2_9:
	add.s32 	%r19, %r14, %r48;
	setp.ge.s32	%p11, %r19, %r25;
	setp.ge.s32	%p12, %r48, %r25;
	or.pred  	%p13, %p11, %p12;
	setp.ge.s32	%p14, %r15, %r26;
	or.pred  	%p15, %p13, %p14;
	@%p15 bra 	BB2_12;

	mul.lo.s32 	%r20, %r48, %r26;
	mul.lo.s32 	%r21, %r19, %r26;
	mov.u32 	%r51, %r15;

BB2_11:
	add.s32 	%r46, %r51, %r20;
	mul.wide.s32 	%rd10, %r46, 4;
	add.s64 	%rd11, %rd2, %rd10;
	ld.global.f32 	%f3, [%rd11];
	add.s32 	%r47, %r51, %r21;
	mul.wide.s32 	%rd12, %r47, 4;
	add.s64 	%rd13, %rd1, %rd12;
	ld.global.f32 	%f4, [%rd13];
	st.global.f32 	[%rd11], %f4;
	add.s64 	%rd14, %rd1, %rd10;
	st.global.f32 	[%rd14], %f3;
	add.s32 	%r51, %r16, %r51;
	setp.lt.s32	%p16, %r51, %r26;
	@%p16 bra 	BB2_11;

BB2_12:
	add.s32 	%r48, %r17, %r48;
	setp.lt.s32	%p17, %r48, %r3;
	@%p17 bra 	BB2_9;
	bra.uni 	BB2_13;

BB2_1:
	setp.ge.s32	%p2, %r48, %r3;
	@%p2 bra 	BB2_13;

	mov.u32 	%r33, %ctaid.y;
	mov.u32 	%r34, %ntid.y;
	mov.u32 	%r35, %tid.y;
	mad.lo.s32 	%r4, %r34, %r33, %r35;
	mov.u32 	%r36, %nctaid.y;
	mul.lo.s32 	%r5, %r36, %r34;
	mov.u32 	%r37, %nctaid.x;
	mul.lo.s32 	%r6, %r37, %r1;

BB2_3:
	add.s32 	%r8, %r3, %r48;
	setp.ge.s32	%p3, %r8, %r25;
	setp.ge.s32	%p4, %r4, %r26;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB2_6;

	mul.lo.s32 	%r9, %r8, %r26;
	setp.gt.s32	%p6, %r27, 0;
	selp.b32	%r38, %r48, %r8, %p6;
	mul.lo.s32 	%r10, %r38, %r26;
	mov.u32 	%r49, %r4;

BB2_5:
	add.s32 	%r39, %r49, %r9;
	mul.wide.s32 	%rd5, %r39, 4;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f1, [%rd6];
	add.s32 	%r40, %r49, %r10;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd1, %rd7;
	ld.global.f32 	%f2, [%rd8];
	st.global.f32 	[%rd6], %f2;
	add.s64 	%rd9, %rd1, %rd5;
	st.global.f32 	[%rd9], %f1;
	add.s32 	%r49, %r5, %r49;
	setp.lt.s32	%p7, %r49, %r26;
	@%p7 bra 	BB2_5;

BB2_6:
	add.s32 	%r48, %r6, %r48;
	setp.lt.s32	%p8, %r48, %r3;
	@%p8 bra 	BB2_3;

BB2_13:
	ret;
}

	// .globl	ShapetoBatch4DNHWC
.visible .entry ShapetoBatch4DNHWC(
	.param .u32 ShapetoBatch4DNHWC_param_0,
	.param .u32 ShapetoBatch4DNHWC_param_1,
	.param .u32 ShapetoBatch4DNHWC_param_2,
	.param .u32 ShapetoBatch4DNHWC_param_3,
	.param .u32 ShapetoBatch4DNHWC_param_4,
	.param .u32 ShapetoBatch4DNHWC_param_5,
	.param .u32 ShapetoBatch4DNHWC_param_6,
	.param .u32 ShapetoBatch4DNHWC_param_7,
	.param .u32 ShapetoBatch4DNHWC_param_8,
	.param .u32 ShapetoBatch4DNHWC_param_9,
	.param .u32 ShapetoBatch4DNHWC_param_10,
	.param .u32 ShapetoBatch4DNHWC_param_11,
	.param .u64 ShapetoBatch4DNHWC_param_12,
	.param .u64 ShapetoBatch4DNHWC_param_13,
	.param .u32 ShapetoBatch4DNHWC_param_14,
	.param .u32 ShapetoBatch4DNHWC_param_15,
	.param .u8 ShapetoBatch4DNHWC_param_16
)
{
	.reg .pred 	%p<23>;
	.reg .b16 	%rs<3>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<101>;
	.reg .b64 	%rd<13>;


	ld.param.u32 	%r51, [ShapetoBatch4DNHWC_param_0];
	ld.param.u32 	%r52, [ShapetoBatch4DNHWC_param_1];
	ld.param.u32 	%r53, [ShapetoBatch4DNHWC_param_2];
	ld.param.u32 	%r54, [ShapetoBatch4DNHWC_param_3];
	ld.param.u32 	%r55, [ShapetoBatch4DNHWC_param_4];
	ld.param.u32 	%r56, [ShapetoBatch4DNHWC_param_5];
	ld.param.u32 	%r57, [ShapetoBatch4DNHWC_param_6];
	ld.param.u32 	%r58, [ShapetoBatch4DNHWC_param_7];
	ld.param.u32 	%r59, [ShapetoBatch4DNHWC_param_8];
	ld.param.u32 	%r60, [ShapetoBatch4DNHWC_param_9];
	ld.param.u32 	%r61, [ShapetoBatch4DNHWC_param_10];
	ld.param.u32 	%r62, [ShapetoBatch4DNHWC_param_11];
	ld.param.u64 	%rd4, [ShapetoBatch4DNHWC_param_12];
	ld.param.u64 	%rd5, [ShapetoBatch4DNHWC_param_13];
	ld.param.u32 	%r63, [ShapetoBatch4DNHWC_param_14];
	ld.param.u32 	%r64, [ShapetoBatch4DNHWC_param_15];
	ld.param.s8 	%rs1, [ShapetoBatch4DNHWC_param_16];
	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd5;
	setp.lt.s32	%p4, %r56, 1;
	@%p4 bra 	BB3_27;

	mov.u32 	%r66, %ctaid.x;
	mov.u32 	%r67, %ntid.x;
	mov.u32 	%r68, %tid.x;
	mad.lo.s32 	%r1, %r67, %r66, %r68;
	mov.u32 	%r69, %ntid.y;
	mov.u32 	%r70, %ctaid.y;
	mov.u32 	%r71, %tid.y;
	mad.lo.s32 	%r2, %r69, %r70, %r71;
	mov.u32 	%r72, %nctaid.x;
	mul.lo.s32 	%r3, %r72, %r67;
	mov.u32 	%r73, %ntid.z;
	mov.u32 	%r74, %ctaid.z;
	mov.u32 	%r75, %tid.z;
	mad.lo.s32 	%r4, %r73, %r74, %r75;
	mov.u32 	%r76, %nctaid.y;
	mul.lo.s32 	%r5, %r76, %r69;
	mov.u32 	%r77, %nctaid.z;
	mul.lo.s32 	%r10, %r77, %r73;
	mad.lo.s32 	%r9, %r74, %r73, %r75;
	mov.u32 	%r90, 0;
	and.b16  	%rs2, %rs1, 255;

BB3_2:
	setp.lt.s32	%p5, %r59, 1;
	@%p5 bra 	BB3_26;

	mul.lo.s32 	%r79, %r57, %r90;
	add.s32 	%r14, %r4, %r79;
	mul.lo.s32 	%r80, %r58, %r90;
	add.s32 	%r15, %r4, %r80;
	mov.u32 	%r91, 0;

BB3_4:
	setp.lt.s32	%p6, %r60, 1;
	@%p6 bra 	BB3_25;

	mul.lo.s32 	%r19, %r91, %r61;
	mul.lo.s32 	%r20, %r60, %r91;
	mov.u32 	%r92, 0;

BB3_6:
	setp.ge.s32	%p7, %r1, %r51;
	@%p7 bra 	BB3_24;

	mul.lo.s32 	%r22, %r92, %r62;
	add.s32 	%r82, %r20, %r92;
	mul.lo.s32 	%r23, %r51, %r82;
	mov.u32 	%r93, %r1;

BB3_8:
	setp.ge.s32	%p8, %r2, %r52;
	@%p8 bra 	BB3_23;

	setp.gt.s32	%p9, %r64, 0;
	add.s32 	%r25, %r93, %r19;
	setp.lt.s32	%p10, %r25, %r54;
	and.pred  	%p1, %p9, %p10;
	add.s32 	%r83, %r23, %r93;
	mul.lo.s32 	%r26, %r52, %r83;
	mul.lo.s32 	%r27, %r54, %r25;
	mov.u32 	%r94, %r2;

BB3_10:
	setp.ge.s32	%p11, %r4, %r53;
	@%p11 bra 	BB3_22;

	add.s32 	%r29, %r94, %r22;
	setp.eq.s16	%p12, %rs2, 0;
	@%p12 bra 	BB3_20;
	bra.uni 	BB3_12;

BB3_20:
	add.s32 	%r88, %r29, %r27;
	mad.lo.s32 	%r99, %r53, %r88, %r15;
	add.s32 	%r89, %r26, %r94;
	mad.lo.s32 	%r98, %r53, %r89, %r14;
	mov.u32 	%r100, %r9;

BB3_21:
	mul.wide.s32 	%rd9, %r98, 4;
	add.s64 	%rd10, %rd2, %rd9;
	mul.wide.s32 	%rd11, %r99, 4;
	add.s64 	%rd12, %rd1, %rd11;
	ld.global.f32 	%f2, [%rd12];
	ld.global.f32 	%f3, [%rd10];
	add.f32 	%f4, %f3, %f2;
	st.global.f32 	[%rd12], %f4;
	add.s32 	%r99, %r99, %r10;
	add.s32 	%r98, %r98, %r10;
	add.s32 	%r100, %r100, %r10;
	setp.lt.s32	%p17, %r100, %r53;
	@%p17 bra 	BB3_21;
	bra.uni 	BB3_22;

BB3_12:
	setp.lt.s32	%p13, %r29, %r55;
	add.s32 	%r84, %r26, %r94;
	mad.lo.s32 	%r97, %r53, %r84, %r14;
	add.s32 	%r85, %r29, %r27;
	mad.lo.s32 	%r96, %r53, %r85, %r15;
	setp.gt.s32	%p14, %r63, 0;
	and.pred  	%p2, %p14, %p13;
	and.pred  	%p3, %p10, %p13;
	mov.u32 	%r95, %r9;

BB3_13:
	mul.wide.s32 	%rd6, %r97, 4;
	add.s64 	%rd3, %rd2, %rd6;
	@%p3 bra 	BB3_18;
	bra.uni 	BB3_14;

BB3_18:
	mul.wide.s32 	%rd7, %r96, 4;
	add.s64 	%rd8, %rd1, %rd7;
	ld.global.f32 	%f1, [%rd8];
	st.global.f32 	[%rd3], %f1;
	bra.uni 	BB3_19;

BB3_14:
	@!%p2 bra 	BB3_16;
	bra.uni 	BB3_15;

BB3_15:
	mov.u32 	%r86, 0;
	st.global.u32 	[%rd3], %r86;

BB3_16:
	@!%p1 bra 	BB3_19;
	bra.uni 	BB3_17;

BB3_17:
	mov.u32 	%r87, 0;
	st.global.u32 	[%rd3], %r87;

BB3_19:
	add.s32 	%r97, %r97, %r10;
	add.s32 	%r96, %r96, %r10;
	add.s32 	%r95, %r95, %r10;
	setp.lt.s32	%p16, %r95, %r53;
	@%p16 bra 	BB3_13;

BB3_22:
	add.s32 	%r94, %r5, %r94;
	setp.lt.s32	%p18, %r94, %r52;
	@%p18 bra 	BB3_10;

BB3_23:
	add.s32 	%r93, %r3, %r93;
	setp.lt.s32	%p19, %r93, %r51;
	@%p19 bra 	BB3_8;

BB3_24:
	add.s32 	%r92, %r92, 1;
	setp.lt.s32	%p20, %r92, %r60;
	@%p20 bra 	BB3_6;

BB3_25:
	add.s32 	%r91, %r91, 1;
	setp.lt.s32	%p21, %r91, %r59;
	@%p21 bra 	BB3_4;

BB3_26:
	add.s32 	%r90, %r90, 1;
	setp.lt.s32	%p22, %r90, %r56;
	@%p22 bra 	BB3_2;

BB3_27:
	ret;
}

	// .globl	ShapetoBatch4DNCHW
.visible .entry ShapetoBatch4DNCHW(
	.param .u32 ShapetoBatch4DNCHW_param_0,
	.param .u32 ShapetoBatch4DNCHW_param_1,
	.param .u32 ShapetoBatch4DNCHW_param_2,
	.param .u32 ShapetoBatch4DNCHW_param_3,
	.param .u32 ShapetoBatch4DNCHW_param_4,
	.param .u32 ShapetoBatch4DNCHW_param_5,
	.param .u32 ShapetoBatch4DNCHW_param_6,
	.param .u32 ShapetoBatch4DNCHW_param_7,
	.param .u32 ShapetoBatch4DNCHW_param_8,
	.param .u32 ShapetoBatch4DNCHW_param_9,
	.param .u32 ShapetoBatch4DNCHW_param_10,
	.param .u32 ShapetoBatch4DNCHW_param_11,
	.param .u64 ShapetoBatch4DNCHW_param_12,
	.param .u64 ShapetoBatch4DNCHW_param_13,
	.param .u32 ShapetoBatch4DNCHW_param_14,
	.param .u32 ShapetoBatch4DNCHW_param_15,
	.param .u8 ShapetoBatch4DNCHW_param_16
)
{
	.reg .pred 	%p<24>;
	.reg .b16 	%rs<3>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<103>;
	.reg .b64 	%rd<13>;


	ld.param.u32 	%r52, [ShapetoBatch4DNCHW_param_0];
	ld.param.u32 	%r53, [ShapetoBatch4DNCHW_param_1];
	ld.param.u32 	%r54, [ShapetoBatch4DNCHW_param_2];
	ld.param.u32 	%r55, [ShapetoBatch4DNCHW_param_3];
	ld.param.u32 	%r56, [ShapetoBatch4DNCHW_param_4];
	ld.param.u32 	%r57, [ShapetoBatch4DNCHW_param_5];
	ld.param.u32 	%r58, [ShapetoBatch4DNCHW_param_6];
	ld.param.u32 	%r59, [ShapetoBatch4DNCHW_param_7];
	ld.param.u32 	%r60, [ShapetoBatch4DNCHW_param_8];
	ld.param.u32 	%r61, [ShapetoBatch4DNCHW_param_9];
	ld.param.u32 	%r62, [ShapetoBatch4DNCHW_param_10];
	ld.param.u32 	%r63, [ShapetoBatch4DNCHW_param_11];
	ld.param.u64 	%rd4, [ShapetoBatch4DNCHW_param_12];
	ld.param.u64 	%rd5, [ShapetoBatch4DNCHW_param_13];
	ld.param.u32 	%r64, [ShapetoBatch4DNCHW_param_14];
	ld.param.u32 	%r65, [ShapetoBatch4DNCHW_param_15];
	ld.param.s8 	%rs1, [ShapetoBatch4DNCHW_param_16];
	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd5;
	setp.lt.s32	%p2, %r57, 1;
	@%p2 bra 	BB4_27;

	mov.u32 	%r67, %ctaid.x;
	mov.u32 	%r68, %ntid.x;
	mov.u32 	%r69, %tid.x;
	mad.lo.s32 	%r1, %r68, %r67, %r69;
	mov.u32 	%r70, %ntid.y;
	mov.u32 	%r71, %ctaid.y;
	mov.u32 	%r72, %tid.y;
	mad.lo.s32 	%r2, %r70, %r71, %r72;
	mov.u32 	%r73, %nctaid.x;
	mul.lo.s32 	%r3, %r73, %r68;
	mov.u32 	%r74, %ntid.z;
	mov.u32 	%r75, %ctaid.z;
	mov.u32 	%r76, %tid.z;
	mad.lo.s32 	%r4, %r74, %r75, %r76;
	mov.u32 	%r77, %nctaid.y;
	mul.lo.s32 	%r5, %r77, %r70;
	mov.u32 	%r78, %nctaid.z;
	mul.lo.s32 	%r11, %r78, %r74;
	mad.lo.s32 	%r10, %r75, %r74, %r76;
	mov.u32 	%r91, 0;
	and.b16  	%rs2, %rs1, 255;

BB4_2:
	setp.lt.s32	%p3, %r60, 1;
	@%p3 bra 	BB4_26;

	mul.lo.s32 	%r80, %r58, %r91;
	add.s32 	%r14, %r4, %r80;
	mad.lo.s32 	%r15, %r59, %r91, %r4;
	mov.u32 	%r92, 0;

BB4_4:
	setp.lt.s32	%p4, %r61, 1;
	@%p4 bra 	BB4_25;

	mul.lo.s32 	%r18, %r92, %r62;
	mul.lo.s32 	%r19, %r61, %r92;
	mov.u32 	%r93, 0;

BB4_6:
	setp.ge.s32	%p5, %r1, %r52;
	@%p5 bra 	BB4_24;

	add.s32 	%r82, %r19, %r93;
	mul.lo.s32 	%r21, %r54, %r82;
	mul.lo.s32 	%r83, %r63, %r93;
	add.s32 	%r22, %r15, %r83;
	add.s32 	%r23, %r4, %r83;
	mov.u32 	%r94, %r1;

BB4_8:
	setp.ge.s32	%p6, %r2, %r53;
	@%p6 bra 	BB4_23;

	add.s32 	%r84, %r21, %r94;
	mul.lo.s32 	%r25, %r52, %r84;
	mul.lo.s32 	%r26, %r55, %r94;
	mov.u32 	%r95, %r2;

BB4_10:
	setp.ge.s32	%p7, %r4, %r54;
	@%p7 bra 	BB4_22;

	add.s32 	%r28, %r95, %r18;
	setp.eq.s16	%p8, %rs2, 0;
	@%p8 bra 	BB4_20;
	bra.uni 	BB4_12;

BB4_20:
	add.s32 	%r89, %r25, %r95;
	mad.lo.s32 	%r101, %r53, %r89, %r14;
	add.s32 	%r90, %r28, %r26;
	mad.lo.s32 	%r100, %r56, %r90, %r22;
	mov.u32 	%r102, %r10;

BB4_21:
	mul.wide.s32 	%rd9, %r101, 4;
	add.s64 	%rd10, %rd2, %rd9;
	mul.wide.s32 	%rd11, %r100, 4;
	add.s64 	%rd12, %rd1, %rd11;
	ld.global.f32 	%f2, [%rd12];
	ld.global.f32 	%f3, [%rd10];
	add.f32 	%f4, %f3, %f2;
	st.global.f32 	[%rd12], %f4;
	add.s32 	%r101, %r101, %r11;
	add.s32 	%r100, %r100, %r11;
	add.s32 	%r102, %r102, %r11;
	setp.lt.s32	%p18, %r102, %r54;
	@%p18 bra 	BB4_21;
	bra.uni 	BB4_22;

BB4_12:
	add.s32 	%r85, %r25, %r95;
	mad.lo.s32 	%r99, %r53, %r85, %r14;
	add.s32 	%r86, %r28, %r26;
	mad.lo.s32 	%r98, %r56, %r86, %r22;
	setp.lt.s32	%p9, %r28, %r55;
	setp.gt.s32	%p10, %r65, 0;
	and.pred  	%p1, %p10, %p9;
	mov.u32 	%r96, %r10;
	mov.u32 	%r97, %r23;

BB4_13:
	setp.lt.s32	%p11, %r97, %r56;
	and.pred  	%p13, %p9, %p11;
	mul.wide.s32 	%rd6, %r99, 4;
	add.s64 	%rd3, %rd2, %rd6;
	@%p13 bra 	BB4_18;
	bra.uni 	BB4_14;

BB4_18:
	mul.wide.s32 	%rd7, %r98, 4;
	add.s64 	%rd8, %rd1, %rd7;
	ld.global.f32 	%f1, [%rd8];
	st.global.f32 	[%rd3], %f1;
	bra.uni 	BB4_19;

BB4_14:
	setp.ge.s32	%p14, %r97, %r56;
	setp.lt.s32	%p15, %r64, 1;
	or.pred  	%p16, %p15, %p14;
	@%p16 bra 	BB4_16;

	mov.u32 	%r87, 0;
	st.global.u32 	[%rd3], %r87;

BB4_16:
	@!%p1 bra 	BB4_19;
	bra.uni 	BB4_17;

BB4_17:
	mov.u32 	%r88, 0;
	st.global.u32 	[%rd3], %r88;

BB4_19:
	add.s32 	%r99, %r99, %r11;
	add.s32 	%r98, %r98, %r11;
	add.s32 	%r97, %r97, %r11;
	add.s32 	%r96, %r96, %r11;
	setp.lt.s32	%p17, %r96, %r54;
	@%p17 bra 	BB4_13;

BB4_22:
	add.s32 	%r95, %r5, %r95;
	setp.lt.s32	%p19, %r95, %r53;
	@%p19 bra 	BB4_10;

BB4_23:
	add.s32 	%r94, %r3, %r94;
	setp.lt.s32	%p20, %r94, %r52;
	@%p20 bra 	BB4_8;

BB4_24:
	add.s32 	%r93, %r93, 1;
	setp.lt.s32	%p21, %r93, %r61;
	@%p21 bra 	BB4_6;

BB4_25:
	add.s32 	%r92, %r92, 1;
	setp.lt.s32	%p22, %r92, %r60;
	@%p22 bra 	BB4_4;

BB4_26:
	add.s32 	%r91, %r91, 1;
	setp.lt.s32	%p23, %r91, %r57;
	@%p23 bra 	BB4_2;

BB4_27:
	ret;
}

	// .globl	NearestNeighborNHWC
.visible .entry NearestNeighborNHWC(
	.param .u32 NearestNeighborNHWC_param_0,
	.param .u32 NearestNeighborNHWC_param_1,
	.param .u64 NearestNeighborNHWC_param_2,
	.param .u32 NearestNeighborNHWC_param_3,
	.param .u32 NearestNeighborNHWC_param_4,
	.param .u32 NearestNeighborNHWC_param_5,
	.param .u32 NearestNeighborNHWC_param_6,
	.param .u32 NearestNeighborNHWC_param_7,
	.param .f32 NearestNeighborNHWC_param_8,
	.param .f32 NearestNeighborNHWC_param_9,
	.param .u64 NearestNeighborNHWC_param_10
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<30>;
	.reg .b32 	%r<38>;
	.reg .b64 	%rd<9>;


	ld.param.u32 	%r8, [NearestNeighborNHWC_param_0];
	ld.param.u32 	%r9, [NearestNeighborNHWC_param_1];
	ld.param.u64 	%rd1, [NearestNeighborNHWC_param_2];
	ld.param.u32 	%r10, [NearestNeighborNHWC_param_3];
	ld.param.u32 	%r11, [NearestNeighborNHWC_param_4];
	ld.param.u32 	%r12, [NearestNeighborNHWC_param_5];
	ld.param.u32 	%r13, [NearestNeighborNHWC_param_6];
	ld.param.u32 	%r14, [NearestNeighborNHWC_param_7];
	ld.param.f32 	%f13, [NearestNeighborNHWC_param_8];
	ld.param.f32 	%f14, [NearestNeighborNHWC_param_9];
	ld.param.u64 	%rd2, [NearestNeighborNHWC_param_10];
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %ntid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r37, %r16, %r15, %r17;
	setp.ge.s32	%p1, %r37, %r9;
	@%p1 bra 	BB5_11;

	add.s32 	%r18, %r10, -1;
	cvt.rn.f32.s32	%f1, %r18;
	add.s32 	%r19, %r11, -1;
	cvt.rn.f32.s32	%f2, %r19;
	cvta.to.global.u64 	%rd3, %rd1;
	cvta.to.global.u64 	%rd6, %rd2;

BB5_2:
	rem.s32 	%r3, %r37, %r12;
	div.s32 	%r20, %r37, %r12;
	rem.s32 	%r4, %r20, %r14;
	div.s32 	%r21, %r20, %r14;
	rem.s32 	%r22, %r21, %r13;
	div.s32 	%r5, %r21, %r13;
	cvt.rn.f32.s32	%f15, %r22;
	mul.f32 	%f3, %f15, %f13;
	setp.eq.s32	%p2, %r8, 0;
	@%p2 bra 	BB5_5;
	bra.uni 	BB5_3;

BB5_5:
	cvt.rmi.f32.f32	%f28, %f3;
	bra.uni 	BB5_6;

BB5_3:
	abs.f32 	%f16, %f3;
	mov.b32 	 %r23, %f3;
	and.b32  	%r24, %r23, -2147483648;
	or.b32  	%r25, %r24, 1056964608;
	mov.b32 	 %f17, %r25;
	add.f32 	%f18, %f3, %f17;
	cvt.rzi.f32.f32	%f19, %f18;
	setp.gt.f32	%p3, %f16, 0f4B000000;
	selp.f32	%f28, %f3, %f19, %p3;
	setp.geu.f32	%p4, %f16, 0f3F000000;
	@%p4 bra 	BB5_6;

	cvt.rzi.f32.f32	%f28, %f3;

BB5_6:
	min.f32 	%f20, %f28, %f1;
	cvt.rzi.s32.f32	%r6, %f20;
	cvt.rn.f32.s32	%f21, %r4;
	mul.f32 	%f8, %f21, %f14;
	@%p2 bra 	BB5_9;
	bra.uni 	BB5_7;

BB5_9:
	cvt.rmi.f32.f32	%f29, %f8;
	bra.uni 	BB5_10;

BB5_7:
	abs.f32 	%f22, %f8;
	mov.b32 	 %r26, %f8;
	and.b32  	%r27, %r26, -2147483648;
	or.b32  	%r28, %r27, 1056964608;
	mov.b32 	 %f23, %r28;
	add.f32 	%f24, %f8, %f23;
	cvt.rzi.f32.f32	%f25, %f24;
	setp.gt.f32	%p6, %f22, 0f4B000000;
	selp.f32	%f29, %f8, %f25, %p6;
	setp.geu.f32	%p7, %f22, 0f3F000000;
	@%p7 bra 	BB5_10;

	cvt.rzi.f32.f32	%f29, %f8;

BB5_10:
	mul.lo.s32 	%r29, %r11, %r10;
	mul.lo.s32 	%r30, %r29, %r12;
	min.f32 	%f26, %f29, %f2;
	cvt.rzi.s32.f32	%r31, %f26;
	mad.lo.s32 	%r32, %r6, %r11, %r31;
	mad.lo.s32 	%r33, %r32, %r12, %r3;
	mad.lo.s32 	%r34, %r30, %r5, %r33;
	mul.wide.s32 	%rd4, %r34, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.f32 	%f27, [%rd5];
	mul.wide.s32 	%rd7, %r37, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f27;
	mov.u32 	%r36, %nctaid.x;
	mad.lo.s32 	%r37, %r36, %r16, %r37;
	setp.lt.s32	%p8, %r37, %r9;
	@%p8 bra 	BB5_2;

BB5_11:
	ret;
}

	// .globl	NearestNeighborNCHW
.visible .entry NearestNeighborNCHW(
	.param .u32 NearestNeighborNCHW_param_0,
	.param .u32 NearestNeighborNCHW_param_1,
	.param .u64 NearestNeighborNCHW_param_2,
	.param .u32 NearestNeighborNCHW_param_3,
	.param .u32 NearestNeighborNCHW_param_4,
	.param .u32 NearestNeighborNCHW_param_5,
	.param .u32 NearestNeighborNCHW_param_6,
	.param .u32 NearestNeighborNCHW_param_7,
	.param .f32 NearestNeighborNCHW_param_8,
	.param .f32 NearestNeighborNCHW_param_9,
	.param .u64 NearestNeighborNCHW_param_10
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<30>;
	.reg .b32 	%r<37>;
	.reg .b64 	%rd<9>;


	ld.param.u32 	%r8, [NearestNeighborNCHW_param_0];
	ld.param.u32 	%r9, [NearestNeighborNCHW_param_1];
	ld.param.u64 	%rd1, [NearestNeighborNCHW_param_2];
	ld.param.u32 	%r10, [NearestNeighborNCHW_param_3];
	ld.param.u32 	%r11, [NearestNeighborNCHW_param_4];
	ld.param.u32 	%r12, [NearestNeighborNCHW_param_5];
	ld.param.u32 	%r13, [NearestNeighborNCHW_param_6];
	ld.param.u32 	%r14, [NearestNeighborNCHW_param_7];
	ld.param.f32 	%f13, [NearestNeighborNCHW_param_8];
	ld.param.f32 	%f14, [NearestNeighborNCHW_param_9];
	ld.param.u64 	%rd2, [NearestNeighborNCHW_param_10];
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %ntid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r36, %r16, %r15, %r17;
	setp.ge.s32	%p1, %r36, %r9;
	@%p1 bra 	BB6_11;

	add.s32 	%r18, %r10, -1;
	cvt.rn.f32.s32	%f1, %r18;
	add.s32 	%r19, %r11, -1;
	cvt.rn.f32.s32	%f2, %r19;
	cvta.to.global.u64 	%rd3, %rd1;
	cvta.to.global.u64 	%rd6, %rd2;

BB6_2:
	rem.s32 	%r3, %r36, %r14;
	div.s32 	%r20, %r36, %r14;
	rem.s32 	%r21, %r20, %r13;
	div.s32 	%r4, %r20, %r13;
	rem.s32 	%r5, %r4, %r12;
	cvt.rn.f32.s32	%f15, %r21;
	mul.f32 	%f3, %f15, %f13;
	setp.eq.s32	%p2, %r8, 0;
	@%p2 bra 	BB6_5;
	bra.uni 	BB6_3;

BB6_5:
	cvt.rmi.f32.f32	%f28, %f3;
	bra.uni 	BB6_6;

BB6_3:
	abs.f32 	%f16, %f3;
	mov.b32 	 %r22, %f3;
	and.b32  	%r23, %r22, -2147483648;
	or.b32  	%r24, %r23, 1056964608;
	mov.b32 	 %f17, %r24;
	add.f32 	%f18, %f3, %f17;
	cvt.rzi.f32.f32	%f19, %f18;
	setp.gt.f32	%p3, %f16, 0f4B000000;
	selp.f32	%f28, %f3, %f19, %p3;
	setp.geu.f32	%p4, %f16, 0f3F000000;
	@%p4 bra 	BB6_6;

	cvt.rzi.f32.f32	%f28, %f3;

BB6_6:
	min.f32 	%f20, %f28, %f1;
	cvt.rzi.s32.f32	%r6, %f20;
	cvt.rn.f32.s32	%f21, %r3;
	mul.f32 	%f8, %f21, %f14;
	@%p2 bra 	BB6_9;
	bra.uni 	BB6_7;

BB6_9:
	cvt.rmi.f32.f32	%f29, %f8;
	bra.uni 	BB6_10;

BB6_7:
	abs.f32 	%f22, %f8;
	mov.b32 	 %r25, %f8;
	and.b32  	%r26, %r25, -2147483648;
	or.b32  	%r27, %r26, 1056964608;
	mov.b32 	 %f23, %r27;
	add.f32 	%f24, %f8, %f23;
	cvt.rzi.f32.f32	%f25, %f24;
	setp.gt.f32	%p6, %f22, 0f4B000000;
	selp.f32	%f29, %f8, %f25, %p6;
	setp.geu.f32	%p7, %f22, 0f3F000000;
	@%p7 bra 	BB6_10;

	cvt.rzi.f32.f32	%f29, %f8;

BB6_10:
	sub.s32 	%r28, %r4, %r5;
	mul.lo.s32 	%r29, %r11, %r10;
	min.f32 	%f26, %f29, %f2;
	cvt.rzi.s32.f32	%r30, %f26;
	mad.lo.s32 	%r31, %r5, %r10, %r6;
	mad.lo.s32 	%r32, %r31, %r11, %r30;
	mad.lo.s32 	%r33, %r29, %r28, %r32;
	mul.wide.s32 	%rd4, %r33, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.f32 	%f27, [%rd5];
	mul.wide.s32 	%rd7, %r36, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f27;
	mov.u32 	%r35, %nctaid.x;
	mad.lo.s32 	%r36, %r35, %r16, %r36;
	setp.lt.s32	%p8, %r36, %r9;
	@%p8 bra 	BB6_2;

BB6_11:
	ret;
}

	// .globl	NearestNeighborNCHWBack
.visible .entry NearestNeighborNCHWBack(
	.param .u32 NearestNeighborNCHWBack_param_0,
	.param .u32 NearestNeighborNCHWBack_param_1,
	.param .u64 NearestNeighborNCHWBack_param_2,
	.param .u32 NearestNeighborNCHWBack_param_3,
	.param .u32 NearestNeighborNCHWBack_param_4,
	.param .u32 NearestNeighborNCHWBack_param_5,
	.param .u32 NearestNeighborNCHWBack_param_6,
	.param .u32 NearestNeighborNCHWBack_param_7,
	.param .f32 NearestNeighborNCHWBack_param_8,
	.param .f32 NearestNeighborNCHWBack_param_9,
	.param .u64 NearestNeighborNCHWBack_param_10
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<37>;
	.reg .b64 	%rd<9>;


	ld.param.u32 	%r8, [NearestNeighborNCHWBack_param_0];
	ld.param.u32 	%r9, [NearestNeighborNCHWBack_param_1];
	ld.param.u64 	%rd1, [NearestNeighborNCHWBack_param_2];
	ld.param.u32 	%r10, [NearestNeighborNCHWBack_param_3];
	ld.param.u32 	%r11, [NearestNeighborNCHWBack_param_4];
	ld.param.u32 	%r12, [NearestNeighborNCHWBack_param_5];
	ld.param.u32 	%r13, [NearestNeighborNCHWBack_param_6];
	ld.param.u32 	%r14, [NearestNeighborNCHWBack_param_7];
	ld.param.f32 	%f13, [NearestNeighborNCHWBack_param_8];
	ld.param.f32 	%f14, [NearestNeighborNCHWBack_param_9];
	ld.param.u64 	%rd2, [NearestNeighborNCHWBack_param_10];
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %ntid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r36, %r16, %r15, %r17;
	setp.ge.s32	%p1, %r36, %r9;
	@%p1 bra 	BB7_11;

	add.s32 	%r18, %r13, -1;
	cvt.rn.f32.s32	%f1, %r18;
	add.s32 	%r19, %r14, -1;
	cvt.rn.f32.s32	%f2, %r19;
	cvta.to.global.u64 	%rd3, %rd1;
	cvta.to.global.u64 	%rd6, %rd2;

BB7_2:
	rem.s32 	%r3, %r36, %r11;
	div.s32 	%r20, %r36, %r11;
	rem.s32 	%r21, %r20, %r10;
	div.s32 	%r4, %r20, %r10;
	rem.s32 	%r5, %r4, %r12;
	cvt.rn.f32.s32	%f15, %r21;
	mul.f32 	%f3, %f15, %f13;
	setp.eq.s32	%p2, %r8, 0;
	@%p2 bra 	BB7_5;
	bra.uni 	BB7_3;

BB7_5:
	cvt.rmi.f32.f32	%f29, %f3;
	bra.uni 	BB7_6;

BB7_3:
	abs.f32 	%f16, %f3;
	mov.b32 	 %r22, %f3;
	and.b32  	%r23, %r22, -2147483648;
	or.b32  	%r24, %r23, 1056964608;
	mov.b32 	 %f17, %r24;
	add.f32 	%f18, %f3, %f17;
	cvt.rzi.f32.f32	%f19, %f18;
	setp.gt.f32	%p3, %f16, 0f4B000000;
	selp.f32	%f29, %f3, %f19, %p3;
	setp.geu.f32	%p4, %f16, 0f3F000000;
	@%p4 bra 	BB7_6;

	cvt.rzi.f32.f32	%f29, %f3;

BB7_6:
	min.f32 	%f20, %f29, %f1;
	cvt.rzi.s32.f32	%r6, %f20;
	cvt.rn.f32.s32	%f21, %r3;
	mul.f32 	%f8, %f21, %f14;
	@%p2 bra 	BB7_9;
	bra.uni 	BB7_7;

BB7_9:
	cvt.rmi.f32.f32	%f30, %f8;
	bra.uni 	BB7_10;

BB7_7:
	abs.f32 	%f22, %f8;
	mov.b32 	 %r25, %f8;
	and.b32  	%r26, %r25, -2147483648;
	or.b32  	%r27, %r26, 1056964608;
	mov.b32 	 %f23, %r27;
	add.f32 	%f24, %f8, %f23;
	cvt.rzi.f32.f32	%f25, %f24;
	setp.gt.f32	%p6, %f22, 0f4B000000;
	selp.f32	%f30, %f8, %f25, %p6;
	setp.geu.f32	%p7, %f22, 0f3F000000;
	@%p7 bra 	BB7_10;

	cvt.rzi.f32.f32	%f30, %f8;

BB7_10:
	sub.s32 	%r28, %r4, %r5;
	mul.lo.s32 	%r29, %r11, %r10;
	min.f32 	%f26, %f30, %f2;
	cvt.rzi.s32.f32	%r30, %f26;
	mad.lo.s32 	%r31, %r5, %r13, %r6;
	mad.lo.s32 	%r32, %r31, %r14, %r30;
	mad.lo.s32 	%r33, %r29, %r28, %r32;
	mul.wide.s32 	%rd4, %r33, 4;
	add.s64 	%rd5, %rd3, %rd4;
	mul.wide.s32 	%rd7, %r36, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.f32 	%f27, [%rd8];
	atom.global.add.f32 	%f28, [%rd5], %f27;
	mov.u32 	%r35, %nctaid.x;
	mad.lo.s32 	%r36, %r35, %r16, %r36;
	setp.lt.s32	%p8, %r36, %r9;
	@%p8 bra 	BB7_2;

BB7_11:
	ret;
}

	// .globl	NearestNeighborNHWCBack
.visible .entry NearestNeighborNHWCBack(
	.param .u32 NearestNeighborNHWCBack_param_0,
	.param .u32 NearestNeighborNHWCBack_param_1,
	.param .u64 NearestNeighborNHWCBack_param_2,
	.param .u32 NearestNeighborNHWCBack_param_3,
	.param .u32 NearestNeighborNHWCBack_param_4,
	.param .u32 NearestNeighborNHWCBack_param_5,
	.param .u32 NearestNeighborNHWCBack_param_6,
	.param .u32 NearestNeighborNHWCBack_param_7,
	.param .f32 NearestNeighborNHWCBack_param_8,
	.param .f32 NearestNeighborNHWCBack_param_9,
	.param .u64 NearestNeighborNHWCBack_param_10
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<38>;
	.reg .b64 	%rd<9>;


	ld.param.u32 	%r8, [NearestNeighborNHWCBack_param_0];
	ld.param.u32 	%r9, [NearestNeighborNHWCBack_param_1];
	ld.param.u64 	%rd1, [NearestNeighborNHWCBack_param_2];
	ld.param.u32 	%r10, [NearestNeighborNHWCBack_param_3];
	ld.param.u32 	%r11, [NearestNeighborNHWCBack_param_4];
	ld.param.u32 	%r12, [NearestNeighborNHWCBack_param_5];
	ld.param.u32 	%r13, [NearestNeighborNHWCBack_param_6];
	ld.param.u32 	%r14, [NearestNeighborNHWCBack_param_7];
	ld.param.f32 	%f13, [NearestNeighborNHWCBack_param_8];
	ld.param.f32 	%f14, [NearestNeighborNHWCBack_param_9];
	ld.param.u64 	%rd2, [NearestNeighborNHWCBack_param_10];
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %ntid.x;
	mov.u32 	%r17, %tid.x;
	mad.lo.s32 	%r37, %r16, %r15, %r17;
	setp.ge.s32	%p1, %r37, %r9;
	@%p1 bra 	BB8_11;

	add.s32 	%r18, %r13, -1;
	cvt.rn.f32.s32	%f1, %r18;
	add.s32 	%r19, %r14, -1;
	cvt.rn.f32.s32	%f2, %r19;
	cvta.to.global.u64 	%rd3, %rd1;
	cvta.to.global.u64 	%rd6, %rd2;

BB8_2:
	rem.s32 	%r3, %r37, %r12;
	div.s32 	%r20, %r37, %r12;
	rem.s32 	%r4, %r20, %r11;
	div.s32 	%r21, %r20, %r11;
	rem.s32 	%r22, %r21, %r10;
	div.s32 	%r5, %r21, %r10;
	cvt.rn.f32.s32	%f15, %r22;
	mul.f32 	%f3, %f15, %f13;
	setp.eq.s32	%p2, %r8, 0;
	@%p2 bra 	BB8_5;
	bra.uni 	BB8_3;

BB8_5:
	cvt.rmi.f32.f32	%f29, %f3;
	bra.uni 	BB8_6;

BB8_3:
	abs.f32 	%f16, %f3;
	mov.b32 	 %r23, %f3;
	and.b32  	%r24, %r23, -2147483648;
	or.b32  	%r25, %r24, 1056964608;
	mov.b32 	 %f17, %r25;
	add.f32 	%f18, %f3, %f17;
	cvt.rzi.f32.f32	%f19, %f18;
	setp.gt.f32	%p3, %f16, 0f4B000000;
	selp.f32	%f29, %f3, %f19, %p3;
	setp.geu.f32	%p4, %f16, 0f3F000000;
	@%p4 bra 	BB8_6;

	cvt.rzi.f32.f32	%f29, %f3;

BB8_6:
	min.f32 	%f20, %f29, %f1;
	cvt.rzi.s32.f32	%r6, %f20;
	cvt.rn.f32.s32	%f21, %r4;
	mul.f32 	%f8, %f21, %f14;
	@%p2 bra 	BB8_9;
	bra.uni 	BB8_7;

BB8_9:
	cvt.rmi.f32.f32	%f30, %f8;
	bra.uni 	BB8_10;

BB8_7:
	abs.f32 	%f22, %f8;
	mov.b32 	 %r26, %f8;
	and.b32  	%r27, %r26, -2147483648;
	or.b32  	%r28, %r27, 1056964608;
	mov.b32 	 %f23, %r28;
	add.f32 	%f24, %f8, %f23;
	cvt.rzi.f32.f32	%f25, %f24;
	setp.gt.f32	%p6, %f22, 0f4B000000;
	selp.f32	%f30, %f8, %f25, %p6;
	setp.geu.f32	%p7, %f22, 0f3F000000;
	@%p7 bra 	BB8_10;

	cvt.rzi.f32.f32	%f30, %f8;

BB8_10:
	mul.lo.s32 	%r29, %r11, %r10;
	mul.lo.s32 	%r30, %r29, %r12;
	min.f32 	%f26, %f30, %f2;
	cvt.rzi.s32.f32	%r31, %f26;
	mad.lo.s32 	%r32, %r6, %r14, %r31;
	mad.lo.s32 	%r33, %r32, %r12, %r3;
	mad.lo.s32 	%r34, %r30, %r5, %r33;
	mul.wide.s32 	%rd4, %r34, 4;
	add.s64 	%rd5, %rd3, %rd4;
	mul.wide.s32 	%rd7, %r37, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.f32 	%f27, [%rd8];
	atom.global.add.f32 	%f28, [%rd5], %f27;
	mov.u32 	%r36, %nctaid.x;
	mad.lo.s32 	%r37, %r36, %r16, %r37;
	setp.lt.s32	%p8, %r37, %r9;
	@%p8 bra 	BB8_2;

BB8_11:
	ret;
}

	// .globl	AdaGrad
.visible .entry AdaGrad(
	.param .u32 AdaGrad_param_0,
	.param .u64 AdaGrad_param_1,
	.param .u64 AdaGrad_param_2,
	.param .u64 AdaGrad_param_3,
	.param .f32 AdaGrad_param_4,
	.param .f32 AdaGrad_param_5,
	.param .f32 AdaGrad_param_6
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<16>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<11>;


	ld.param.u32 	%r6, [AdaGrad_param_0];
	ld.param.u64 	%rd4, [AdaGrad_param_1];
	ld.param.u64 	%rd5, [AdaGrad_param_2];
	ld.param.u64 	%rd6, [AdaGrad_param_3];
	ld.param.f32 	%f1, [AdaGrad_param_4];
	ld.param.f32 	%f2, [AdaGrad_param_5];
	ld.param.f32 	%f3, [AdaGrad_param_6];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB9_3;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd5;
	cvta.to.global.u64 	%rd3, %rd6;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB9_2:
	mul.wide.s32 	%rd7, %r10, 4;
	add.s64 	%rd8, %rd3, %rd7;
	add.s64 	%rd9, %rd2, %rd7;
	ld.global.f32 	%f4, [%rd9];
	ld.global.f32 	%f5, [%rd8];
	fma.rn.f32 	%f6, %f4, %f4, %f5;
	st.global.f32 	[%rd8], %f6;
	ld.global.f32 	%f7, [%rd9];
	mul.f32 	%f8, %f7, %f1;
	sqrt.rn.f32 	%f9, %f6;
	add.f32 	%f10, %f9, %f2;
	div.rn.f32 	%f11, %f8, %f10;
	add.s64 	%rd10, %rd1, %rd7;
	ld.global.f32 	%f12, [%rd10];
	sub.f32 	%f13, %f12, %f11;
	st.global.f32 	[%rd10], %f13;
	ld.global.f32 	%f14, [%rd9];
	mul.f32 	%f15, %f14, %f3;
	st.global.f32 	[%rd9], %f15;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p2, %r10, %r6;
	@%p2 bra 	BB9_2;

BB9_3:
	ret;
}

	// .globl	Adam
.visible .entry Adam(
	.param .u32 Adam_param_0,
	.param .u64 Adam_param_1,
	.param .u64 Adam_param_2,
	.param .u64 Adam_param_3,
	.param .u64 Adam_param_4,
	.param .f32 Adam_param_5,
	.param .f32 Adam_param_6,
	.param .f32 Adam_param_7,
	.param .f32 Adam_param_8,
	.param .f32 Adam_param_9,
	.param .f32 Adam_param_10,
	.param .f32 Adam_param_11
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<27>;
	.reg .b32 	%r<11>;
	.reg .f64 	%fd<12>;
	.reg .b64 	%rd<14>;


	ld.param.u32 	%r6, [Adam_param_0];
	ld.param.u64 	%rd4, [Adam_param_1];
	ld.param.u64 	%rd5, [Adam_param_2];
	ld.param.u64 	%rd6, [Adam_param_3];
	ld.param.u64 	%rd7, [Adam_param_4];
	ld.param.f32 	%f1, [Adam_param_5];
	ld.param.f32 	%f2, [Adam_param_6];
	ld.param.f32 	%f3, [Adam_param_7];
	ld.param.f32 	%f4, [Adam_param_8];
	ld.param.f32 	%f5, [Adam_param_9];
	ld.param.f32 	%f6, [Adam_param_10];
	ld.param.f32 	%f7, [Adam_param_11];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB10_3;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd5;
	cvt.f64.f32	%fd3, %f2;
	mov.f64 	%fd4, 0d3FF0000000000000;
	sub.f64 	%fd1, %fd4, %fd3;
	cvt.f64.f32	%fd5, %f3;
	sub.f64 	%fd2, %fd4, %fd5;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;
	cvta.to.global.u64 	%rd10, %rd7;

BB10_2:
	mul.wide.s32 	%rd8, %r10, 4;
	add.s64 	%rd9, %rd3, %rd8;
	ld.global.f32 	%f8, [%rd9];
	mul.f32 	%f9, %f8, %f2;
	cvt.f64.f32	%fd6, %f9;
	add.s64 	%rd11, %rd10, %rd8;
	ld.global.f32 	%f10, [%rd11];
	cvt.f64.f32	%fd7, %f10;
	fma.rn.f64 	%fd8, %fd1, %fd7, %fd6;
	cvt.rn.f32.f64	%f11, %fd8;
	st.global.f32 	[%rd9], %f11;
	div.rn.f32 	%f12, %f11, %f5;
	add.s64 	%rd12, %rd2, %rd8;
	ld.global.f32 	%f13, [%rd12];
	mul.f32 	%f14, %f13, %f3;
	cvt.f64.f32	%fd9, %f14;
	ld.global.f32 	%f15, [%rd11];
	mul.f32 	%f16, %f15, %f15;
	cvt.f64.f32	%fd10, %f16;
	fma.rn.f64 	%fd11, %fd2, %fd10, %fd9;
	cvt.rn.f32.f64	%f17, %fd11;
	st.global.f32 	[%rd12], %f17;
	div.rn.f32 	%f18, %f17, %f6;
	mul.f32 	%f19, %f12, %f1;
	sqrt.rn.f32 	%f20, %f18;
	add.f32 	%f21, %f20, %f4;
	div.rn.f32 	%f22, %f19, %f21;
	add.s64 	%rd13, %rd1, %rd8;
	ld.global.f32 	%f23, [%rd13];
	sub.f32 	%f24, %f23, %f22;
	st.global.f32 	[%rd13], %f24;
	ld.global.f32 	%f25, [%rd11];
	mul.f32 	%f26, %f25, %f7;
	st.global.f32 	[%rd11], %f26;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p2, %r10, %r6;
	@%p2 bra 	BB10_2;

BB10_3:
	ret;
}

	// .globl	AdaDelta
.visible .entry AdaDelta(
	.param .u32 AdaDelta_param_0,
	.param .u64 AdaDelta_param_1,
	.param .u64 AdaDelta_param_2,
	.param .u64 AdaDelta_param_3,
	.param .u64 AdaDelta_param_4,
	.param .f32 AdaDelta_param_5,
	.param .f32 AdaDelta_param_6,
	.param .f32 AdaDelta_param_7,
	.param .f32 AdaDelta_param_8
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<24>;
	.reg .b32 	%r<15>;
	.reg .f64 	%fd<8>;
	.reg .b64 	%rd<14>;


	ld.param.u32 	%r5, [AdaDelta_param_0];
	ld.param.u64 	%rd2, [AdaDelta_param_1];
	ld.param.u64 	%rd3, [AdaDelta_param_2];
	ld.param.u64 	%rd4, [AdaDelta_param_3];
	ld.param.u64 	%rd5, [AdaDelta_param_4];
	ld.param.f32 	%f1, [AdaDelta_param_6];
	ld.param.f32 	%f2, [AdaDelta_param_7];
	ld.param.f32 	%f3, [AdaDelta_param_8];
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r14, %r7, %r6, %r8;
	setp.ge.s32	%p1, %r14, %r5;
	@%p1 bra 	BB11_3;

	cvt.f64.f32	%fd2, %f2;
	mov.f64 	%fd3, 0d3FF0000000000000;
	sub.f64 	%fd1, %fd3, %fd2;
	mov.u32 	%r11, %nctaid.x;
	mul.lo.s32 	%r1, %r11, %r7;
	cvta.to.global.u64 	%rd1, %rd3;
	cvta.to.global.u64 	%rd8, %rd5;
	cvta.to.global.u64 	%rd10, %rd4;
	cvta.to.global.u64 	%rd12, %rd2;

BB11_2:
	mul.wide.s32 	%rd6, %r14, 4;
	add.s64 	%rd7, %rd1, %rd6;
	ld.global.f32 	%f4, [%rd7];
	mul.f32 	%f5, %f4, %f2;
	cvt.f64.f32	%fd4, %f5;
	add.s64 	%rd9, %rd8, %rd6;
	ld.global.f32 	%f6, [%rd9];
	cvt.f64.f32	%fd5, %f6;
	mul.f64 	%fd6, %fd1, %fd5;
	fma.rn.f64 	%fd7, %fd5, %fd6, %fd4;
	cvt.rn.f32.f64	%f7, %fd7;
	st.global.f32 	[%rd7], %f7;
	add.s64 	%rd11, %rd10, %rd6;
	ld.global.f32 	%f8, [%rd11];
	add.f32 	%f9, %f8, %f1;
	add.f32 	%f10, %f7, %f1;
	div.rn.f32 	%f11, %f9, %f10;
	sqrt.rn.f32 	%f12, %f11;
	ld.global.f32 	%f13, [%rd9];
	mul.f32 	%f14, %f12, %f13;
	mov.f32 	%f15, 0f3F800000;
	sub.f32 	%f16, %f15, %f2;
	mul.f32 	%f17, %f16, %f14;
	mul.f32 	%f18, %f14, %f17;
	fma.rn.f32 	%f19, %f8, %f2, %f18;
	st.global.f32 	[%rd11], %f19;
	add.s64 	%rd13, %rd12, %rd6;
	ld.global.f32 	%f20, [%rd13];
	sub.f32 	%f21, %f20, %f14;
	st.global.f32 	[%rd13], %f21;
	ld.global.f32 	%f22, [%rd9];
	mul.f32 	%f23, %f22, %f3;
	st.global.f32 	[%rd9], %f23;
	add.s32 	%r14, %r1, %r14;
	setp.lt.s32	%p2, %r14, %r5;
	@%p2 bra 	BB11_2;

BB11_3:
	ret;
}

	// .globl	L1L2
.visible .entry L1L2(
	.param .u32 L1L2_param_0,
	.param .u64 L1L2_param_1,
	.param .u64 L1L2_param_2,
	.param .u64 L1L2_param_3,
	.param .u64 L1L2_param_4,
	.param .f32 L1L2_param_5,
	.param .f32 L1L2_param_6,
	.param .f32 L1L2_param_7
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<19>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<12>;


	ld.param.u32 	%r6, [L1L2_param_0];
	ld.param.u64 	%rd5, [L1L2_param_1];
	ld.param.u64 	%rd6, [L1L2_param_2];
	ld.param.u64 	%rd7, [L1L2_param_3];
	ld.param.u64 	%rd8, [L1L2_param_4];
	ld.param.f32 	%f1, [L1L2_param_5];
	ld.param.f32 	%f2, [L1L2_param_6];
	ld.param.f32 	%f3, [L1L2_param_7];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB12_3;

	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd6;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;
	cvta.to.global.u64 	%rd3, %rd7;
	cvta.to.global.u64 	%rd4, %rd8;

BB12_2:
	mul.wide.s32 	%rd9, %r10, 4;
	add.s64 	%rd10, %rd2, %rd9;
	ld.global.f32 	%f4, [%rd10];
	abs.f32 	%f5, %f4;
	mul.f32 	%f6, %f5, %f2;
	atom.global.add.f32 	%f7, [%rd3], %f6;
	ld.global.f32 	%f8, [%rd10];
	mul.f32 	%f9, %f8, %f8;
	mul.f32 	%f10, %f9, %f3;
	mul.f32 	%f11, %f10, 0f3F000000;
	atom.global.add.f32 	%f12, [%rd4], %f11;
	ld.global.f32 	%f13, [%rd10];
	setp.gt.f32	%p2, %f13, 0f00000000;
	selp.f32	%f14, 0f3F800000, 0fBF800000, %p2;
	add.s64 	%rd11, %rd1, %rd9;
	ld.global.f32 	%f15, [%rd11];
	fma.rn.f32 	%f16, %f13, %f3, %f15;
	fma.rn.f32 	%f17, %f14, %f2, %f16;
	div.rn.f32 	%f18, %f17, %f1;
	st.global.f32 	[%rd11], %f18;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB12_2;

BB12_3:
	ret;
}

	// .globl	ThreshForward
.visible .entry ThreshForward(
	.param .u32 ThreshForward_param_0,
	.param .u32 ThreshForward_param_1,
	.param .u64 ThreshForward_param_2,
	.param .u64 ThreshForward_param_3,
	.param .u64 ThreshForward_param_4,
	.param .u64 ThreshForward_param_5,
	.param .u64 ThreshForward_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<9>;
	.reg .b32 	%r<20>;
	.reg .b64 	%rd<21>;


	ld.param.u32 	%r8, [ThreshForward_param_0];
	ld.param.u32 	%r9, [ThreshForward_param_1];
	ld.param.u64 	%rd5, [ThreshForward_param_2];
	ld.param.u64 	%rd6, [ThreshForward_param_3];
	ld.param.u64 	%rd7, [ThreshForward_param_4];
	ld.param.u64 	%rd8, [ThreshForward_param_5];
	ld.param.u64 	%rd9, [ThreshForward_param_6];
	setp.lt.s32	%p1, %r9, 1;
	@%p1 bra 	BB13_8;

	cvta.to.global.u64 	%rd1, %rd7;
	cvta.to.global.u64 	%rd2, %rd5;
	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %nctaid.x;
	mul.lo.s32 	%r1, %r12, %r11;
	mov.u32 	%r18, 0;
	cvta.to.global.u64 	%rd12, %rd8;
	cvta.to.global.u64 	%rd15, %rd6;
	cvta.to.global.u64 	%rd18, %rd9;

BB13_2:
	mov.u32 	%r13, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r19, %r11, %r13, %r15;
	mul.lo.s32 	%r4, %r18, %r8;
	setp.ge.s32	%p2, %r19, %r8;
	@%p2 bra 	BB13_7;

BB13_3:
	add.s32 	%r16, %r19, %r4;
	mul.wide.s32 	%rd10, %r16, 4;
	add.s64 	%rd11, %rd2, %rd10;
	cvt.s64.s32	%rd3, %r19;
	mul.wide.s32 	%rd13, %r19, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.f32 	%f5, [%rd14];
	ld.global.f32 	%f1, [%rd11];
	setp.gt.f32	%p3, %f1, %f5;
	add.s64 	%rd4, %rd15, %rd10;
	@%p3 bra 	BB13_5;
	bra.uni 	BB13_4;

BB13_5:
	add.s64 	%rd20, %rd18, %rd13;
	ld.global.f32 	%f7, [%rd20];
	mul.f32 	%f8, %f1, %f7;
	bra.uni 	BB13_6;

BB13_4:
	add.s64 	%rd17, %rd1, %rd13;
	ld.global.f32 	%f6, [%rd17];
	mul.f32 	%f8, %f6, %f1;

BB13_6:
	st.global.f32 	[%rd4], %f8;
	cvt.u32.u64	%r17, %rd3;
	add.s32 	%r19, %r1, %r17;
	setp.lt.s32	%p4, %r19, %r8;
	@%p4 bra 	BB13_3;

BB13_7:
	add.s32 	%r18, %r18, 1;
	setp.lt.s32	%p5, %r18, %r9;
	@%p5 bra 	BB13_2;

BB13_8:
	ret;
}

	// .globl	ThreshBackward
.visible .entry ThreshBackward(
	.param .u32 ThreshBackward_param_0,
	.param .u32 ThreshBackward_param_1,
	.param .u64 ThreshBackward_param_2,
	.param .u64 ThreshBackward_param_3,
	.param .u64 ThreshBackward_param_4,
	.param .u64 ThreshBackward_param_5,
	.param .u64 ThreshBackward_param_6,
	.param .u64 ThreshBackward_param_7,
	.param .u64 ThreshBackward_param_8,
	.param .u64 ThreshBackward_param_9,
	.param .u64 ThreshBackward_param_10
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<20>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<43>;


	ld.param.u32 	%r6, [ThreshBackward_param_0];
	ld.param.u32 	%r7, [ThreshBackward_param_1];
	ld.param.u64 	%rd2, [ThreshBackward_param_2];
	ld.param.u64 	%rd3, [ThreshBackward_param_3];
	ld.param.u64 	%rd4, [ThreshBackward_param_4];
	ld.param.u64 	%rd5, [ThreshBackward_param_5];
	ld.param.u64 	%rd6, [ThreshBackward_param_6];
	ld.param.u64 	%rd7, [ThreshBackward_param_7];
	ld.param.u64 	%rd8, [ThreshBackward_param_8];
	ld.param.u64 	%rd9, [ThreshBackward_param_9];
	ld.param.u64 	%rd10, [ThreshBackward_param_10];
	setp.lt.s32	%p1, %r7, 1;
	@%p1 bra 	BB14_8;

	mov.u32 	%r17, 0;
	cvta.to.global.u64 	%rd11, %rd2;
	cvta.to.global.u64 	%rd13, %rd7;
	cvta.to.global.u64 	%rd27, %rd9;
	cvta.to.global.u64 	%rd36, %rd10;
	cvta.to.global.u64 	%rd41, %rd8;
	cvta.to.global.u64 	%rd16, %rd5;
	cvta.to.global.u64 	%rd25, %rd6;

BB14_2:
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r18, %r10, %r9, %r11;
	setp.ge.s32	%p2, %r18, %r6;
	@%p2 bra 	BB14_7;

BB14_3:
	mad.lo.s32 	%r12, %r17, %r6, %r18;
	mul.wide.s32 	%rd12, %r12, 4;
	add.s64 	%rd1, %rd11, %rd12;
	mul.wide.s32 	%rd14, %r18, 4;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.f32 	%f1, [%rd15];
	ld.global.f32 	%f2, [%rd1];
	setp.gt.f32	%p3, %f2, %f1;
	@%p3 bra 	BB14_5;
	bra.uni 	BB14_4;

BB14_5:
	add.s64 	%rd29, %rd27, %rd14;
	cvta.to.global.u64 	%rd31, %rd4;
	add.s64 	%rd32, %rd31, %rd12;
	ld.global.f32 	%f10, [%rd32];
	ld.global.f32 	%f11, [%rd29];
	mul.f32 	%f12, %f11, %f10;
	cvta.to.global.u64 	%rd33, %rd3;
	add.s64 	%rd34, %rd33, %rd12;
	st.global.f32 	[%rd34], %f12;
	add.s64 	%rd35, %rd31, %rd14;
	ld.global.f32 	%f13, [%rd1];
	ld.global.f32 	%f14, [%rd35];
	add.s64 	%rd37, %rd36, %rd14;
	ld.global.f32 	%f15, [%rd37];
	fma.rn.f32 	%f16, %f14, %f13, %f15;
	st.global.f32 	[%rd37], %f16;
	bra.uni 	BB14_6;

BB14_4:
	add.s64 	%rd18, %rd16, %rd14;
	cvta.to.global.u64 	%rd20, %rd4;
	add.s64 	%rd21, %rd20, %rd12;
	ld.global.f32 	%f3, [%rd21];
	ld.global.f32 	%f4, [%rd18];
	mul.f32 	%f5, %f4, %f3;
	cvta.to.global.u64 	%rd22, %rd3;
	add.s64 	%rd23, %rd22, %rd12;
	st.global.f32 	[%rd23], %f5;
	add.s64 	%rd24, %rd20, %rd14;
	ld.global.f32 	%f6, [%rd1];
	ld.global.f32 	%f7, [%rd24];
	add.s64 	%rd26, %rd25, %rd14;
	ld.global.f32 	%f8, [%rd26];
	fma.rn.f32 	%f9, %f7, %f6, %f8;
	st.global.f32 	[%rd26], %f9;

BB14_6:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd14;
	add.s64 	%rd42, %rd41, %rd14;
	ld.global.f32 	%f17, [%rd42];
	ld.global.f32 	%f18, [%rd40];
	add.f32 	%f19, %f18, %f17;
	st.global.f32 	[%rd42], %f19;
	mov.u32 	%r16, %nctaid.x;
	mad.lo.s32 	%r18, %r16, %r10, %r18;
	setp.lt.s32	%p4, %r18, %r6;
	@%p4 bra 	BB14_3;

BB14_7:
	add.s32 	%r17, %r17, 1;
	setp.lt.s32	%p5, %r17, %r7;
	@%p5 bra 	BB14_2;

BB14_8:
	ret;
}

	// .globl	PreluForward
.visible .entry PreluForward(
	.param .u32 PreluForward_param_0,
	.param .u32 PreluForward_param_1,
	.param .u64 PreluForward_param_2,
	.param .u64 PreluForward_param_3,
	.param .u64 PreluForward_param_4
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<12>;


	ld.param.u32 	%r8, [PreluForward_param_0];
	ld.param.u32 	%r9, [PreluForward_param_1];
	ld.param.u64 	%rd4, [PreluForward_param_2];
	ld.param.u64 	%rd5, [PreluForward_param_3];
	ld.param.u64 	%rd6, [PreluForward_param_4];
	setp.lt.s32	%p1, %r9, 1;
	@%p1 bra 	BB15_7;

	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd4;
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %ntid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r12, %r11, %r13;
	mov.u32 	%r14, %nctaid.x;
	mul.lo.s32 	%r2, %r14, %r12;
	mov.u32 	%r16, 0;
	cvta.to.global.u64 	%rd9, %rd5;

BB15_2:
	mul.lo.s32 	%r4, %r16, %r8;
	setp.ge.s32	%p2, %r1, %r8;
	mov.u32 	%r17, %r1;
	@%p2 bra 	BB15_6;

BB15_3:
	add.s32 	%r15, %r17, %r4;
	mul.wide.s32 	%rd7, %r15, 4;
	add.s64 	%rd8, %rd2, %rd7;
	ld.global.f32 	%f5, [%rd8];
	setp.gt.f32	%p3, %f5, 0f00000000;
	add.s64 	%rd3, %rd9, %rd7;
	@%p3 bra 	BB15_5;

	mul.wide.s32 	%rd10, %r17, 4;
	add.s64 	%rd11, %rd1, %rd10;
	ld.global.f32 	%f4, [%rd11];
	mul.f32 	%f5, %f4, %f5;

BB15_5:
	st.global.f32 	[%rd3], %f5;
	add.s32 	%r17, %r2, %r17;
	setp.lt.s32	%p4, %r17, %r8;
	@%p4 bra 	BB15_3;

BB15_6:
	add.s32 	%r16, %r16, 1;
	setp.lt.s32	%p5, %r16, %r9;
	@%p5 bra 	BB15_2;

BB15_7:
	ret;
}

	// .globl	PreluBackward
.visible .entry PreluBackward(
	.param .u32 PreluBackward_param_0,
	.param .u32 PreluBackward_param_1,
	.param .u64 PreluBackward_param_2,
	.param .u64 PreluBackward_param_3,
	.param .u64 PreluBackward_param_4,
	.param .u64 PreluBackward_param_5,
	.param .u64 PreluBackward_param_6
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<21>;
	.reg .b64 	%rd<24>;


	ld.param.u32 	%r8, [PreluBackward_param_0];
	ld.param.u32 	%r9, [PreluBackward_param_1];
	ld.param.u64 	%rd3, [PreluBackward_param_2];
	ld.param.u64 	%rd4, [PreluBackward_param_3];
	ld.param.u64 	%rd5, [PreluBackward_param_4];
	ld.param.u64 	%rd6, [PreluBackward_param_5];
	ld.param.u64 	%rd7, [PreluBackward_param_6];
	setp.lt.s32	%p1, %r9, 1;
	@%p1 bra 	BB16_8;

	mov.u32 	%r11, %ntid.x;
	mov.u32 	%r12, %nctaid.x;
	mul.lo.s32 	%r1, %r12, %r11;
	mov.u32 	%r19, 0;
	cvta.to.global.u64 	%rd8, %rd4;
	cvta.to.global.u64 	%rd11, %rd6;
	cvta.to.global.u64 	%rd19, %rd7;

BB16_2:
	mov.u32 	%r13, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r20, %r11, %r13, %r15;
	mul.lo.s32 	%r4, %r19, %r8;
	setp.ge.s32	%p2, %r20, %r8;
	@%p2 bra 	BB16_7;

BB16_3:
	add.s32 	%r16, %r20, %r4;
	mul.wide.s32 	%rd9, %r16, 4;
	add.s64 	%rd1, %rd8, %rd9;
	ld.global.f32 	%f1, [%rd1];
	setp.gt.f32	%p3, %f1, 0f00000000;
	cvta.to.global.u64 	%rd10, %rd5;
	add.s64 	%rd2, %rd10, %rd9;
	@%p3 bra 	BB16_5;
	bra.uni 	BB16_4;

BB16_5:
	ld.global.f32 	%f9, [%rd2];
	mad.lo.s32 	%r18, %r19, %r8, %r20;
	cvta.to.global.u64 	%rd21, %rd3;
	mul.wide.s32 	%rd22, %r18, 4;
	add.s64 	%rd23, %rd21, %rd22;
	st.global.f32 	[%rd23], %f9;
	bra.uni 	BB16_6;

BB16_4:
	mul.wide.s32 	%rd12, %r20, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.f32 	%f2, [%rd2];
	ld.global.f32 	%f3, [%rd13];
	mul.f32 	%f4, %f3, %f2;
	mad.lo.s32 	%r17, %r19, %r8, %r20;
	cvta.to.global.u64 	%rd14, %rd3;
	mul.wide.s32 	%rd15, %r17, 4;
	add.s64 	%rd16, %rd14, %rd15;
	st.global.f32 	[%rd16], %f4;
	add.s64 	%rd18, %rd10, %rd12;
	ld.global.f32 	%f5, [%rd1];
	ld.global.f32 	%f6, [%rd18];
	add.s64 	%rd20, %rd19, %rd12;
	ld.global.f32 	%f7, [%rd20];
	fma.rn.f32 	%f8, %f6, %f5, %f7;
	st.global.f32 	[%rd20], %f8;

BB16_6:
	add.s32 	%r20, %r1, %r20;
	setp.lt.s32	%p4, %r20, %r8;
	@%p4 bra 	BB16_3;

BB16_7:
	add.s32 	%r19, %r19, 1;
	setp.lt.s32	%p5, %r19, %r9;
	@%p5 bra 	BB16_2;

BB16_8:
	ret;
}

	// .globl	LeakyForwardAlphaBeta
.visible .entry LeakyForwardAlphaBeta(
	.param .u32 LeakyForwardAlphaBeta_param_0,
	.param .u64 LeakyForwardAlphaBeta_param_1,
	.param .u64 LeakyForwardAlphaBeta_param_2,
	.param .f32 LeakyForwardAlphaBeta_param_3,
	.param .f32 LeakyForwardAlphaBeta_param_4,
	.param .f32 LeakyForwardAlphaBeta_param_5
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<10>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<8>;


	ld.param.u32 	%r6, [LeakyForwardAlphaBeta_param_0];
	ld.param.u64 	%rd3, [LeakyForwardAlphaBeta_param_1];
	ld.param.u64 	%rd4, [LeakyForwardAlphaBeta_param_2];
	ld.param.f32 	%f1, [LeakyForwardAlphaBeta_param_3];
	ld.param.f32 	%f2, [LeakyForwardAlphaBeta_param_4];
	ld.param.f32 	%f3, [LeakyForwardAlphaBeta_param_5];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB17_3;

	cvta.to.global.u64 	%rd1, %rd3;
	cvta.to.global.u64 	%rd2, %rd4;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB17_2:
	mul.wide.s32 	%rd5, %r10, 4;
	add.s64 	%rd6, %rd2, %rd5;
	add.s64 	%rd7, %rd1, %rd5;
	ld.global.f32 	%f4, [%rd7];
	setp.gt.f32	%p2, %f4, 0f00000000;
	ld.global.f32 	%f5, [%rd6];
	mul.f32 	%f6, %f4, %f1;
	selp.f32	%f7, %f4, %f6, %p2;
	mul.f32 	%f8, %f7, %f2;
	fma.rn.f32 	%f9, %f5, %f3, %f8;
	st.global.f32 	[%rd6], %f9;
	bar.sync 	0;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB17_2;

BB17_3:
	ret;
}

	// .globl	LeakyBackwardAlphaBeta
.visible .entry LeakyBackwardAlphaBeta(
	.param .u32 LeakyBackwardAlphaBeta_param_0,
	.param .u64 LeakyBackwardAlphaBeta_param_1,
	.param .u64 LeakyBackwardAlphaBeta_param_2,
	.param .u64 LeakyBackwardAlphaBeta_param_3,
	.param .f32 LeakyBackwardAlphaBeta_param_4,
	.param .f32 LeakyBackwardAlphaBeta_param_5,
	.param .f32 LeakyBackwardAlphaBeta_param_6
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<11>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<11>;


	ld.param.u32 	%r6, [LeakyBackwardAlphaBeta_param_0];
	ld.param.u64 	%rd4, [LeakyBackwardAlphaBeta_param_1];
	ld.param.u64 	%rd5, [LeakyBackwardAlphaBeta_param_2];
	ld.param.u64 	%rd6, [LeakyBackwardAlphaBeta_param_3];
	ld.param.f32 	%f1, [LeakyBackwardAlphaBeta_param_4];
	ld.param.f32 	%f2, [LeakyBackwardAlphaBeta_param_5];
	ld.param.f32 	%f3, [LeakyBackwardAlphaBeta_param_6];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB18_3;

	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd4;
	cvta.to.global.u64 	%rd3, %rd5;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB18_2:
	mul.wide.s32 	%rd7, %r10, 4;
	add.s64 	%rd8, %rd3, %rd7;
	add.s64 	%rd9, %rd2, %rd7;
	ld.global.f32 	%f4, [%rd9];
	setp.gt.f32	%p2, %f4, 0f00000000;
	add.s64 	%rd10, %rd1, %rd7;
	ld.global.f32 	%f5, [%rd8];
	ld.global.f32 	%f6, [%rd10];
	mul.f32 	%f7, %f6, %f1;
	selp.f32	%f8, %f6, %f7, %p2;
	mul.f32 	%f9, %f8, %f2;
	fma.rn.f32 	%f10, %f5, %f3, %f9;
	st.global.f32 	[%rd8], %f10;
	bar.sync 	0;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB18_2;

BB18_3:
	ret;
}

	// .globl	LeakyForwardAlpha
.visible .entry LeakyForwardAlpha(
	.param .u32 LeakyForwardAlpha_param_0,
	.param .u64 LeakyForwardAlpha_param_1,
	.param .u64 LeakyForwardAlpha_param_2,
	.param .f32 LeakyForwardAlpha_param_3,
	.param .f32 LeakyForwardAlpha_param_4
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<7>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<8>;


	ld.param.u32 	%r6, [LeakyForwardAlpha_param_0];
	ld.param.u64 	%rd3, [LeakyForwardAlpha_param_1];
	ld.param.u64 	%rd4, [LeakyForwardAlpha_param_2];
	ld.param.f32 	%f1, [LeakyForwardAlpha_param_3];
	ld.param.f32 	%f2, [LeakyForwardAlpha_param_4];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB19_3;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd3;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB19_2:
	mul.wide.s32 	%rd5, %r10, 4;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f3, [%rd6];
	setp.gt.f32	%p2, %f3, 0f00000000;
	add.s64 	%rd7, %rd1, %rd5;
	mul.f32 	%f4, %f3, %f1;
	selp.f32	%f5, %f3, %f4, %p2;
	mul.f32 	%f6, %f5, %f2;
	st.global.f32 	[%rd7], %f6;
	bar.sync 	0;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB19_2;

BB19_3:
	ret;
}

	// .globl	LeakyBackwardAlpha
.visible .entry LeakyBackwardAlpha(
	.param .u32 LeakyBackwardAlpha_param_0,
	.param .u64 LeakyBackwardAlpha_param_1,
	.param .u64 LeakyBackwardAlpha_param_2,
	.param .u64 LeakyBackwardAlpha_param_3,
	.param .f32 LeakyBackwardAlpha_param_4,
	.param .f32 LeakyBackwardAlpha_param_5
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<8>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<11>;


	ld.param.u32 	%r6, [LeakyBackwardAlpha_param_0];
	ld.param.u64 	%rd4, [LeakyBackwardAlpha_param_1];
	ld.param.u64 	%rd5, [LeakyBackwardAlpha_param_2];
	ld.param.u64 	%rd6, [LeakyBackwardAlpha_param_3];
	ld.param.f32 	%f1, [LeakyBackwardAlpha_param_4];
	ld.param.f32 	%f2, [LeakyBackwardAlpha_param_5];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB20_3;

	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd4;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB20_2:
	mul.wide.s32 	%rd7, %r10, 4;
	add.s64 	%rd8, %rd3, %rd7;
	ld.global.f32 	%f3, [%rd8];
	setp.gt.f32	%p2, %f3, 0f00000000;
	add.s64 	%rd9, %rd2, %rd7;
	add.s64 	%rd10, %rd1, %rd7;
	ld.global.f32 	%f4, [%rd9];
	mul.f32 	%f5, %f4, %f1;
	selp.f32	%f6, %f4, %f5, %p2;
	mul.f32 	%f7, %f6, %f2;
	st.global.f32 	[%rd10], %f7;
	bar.sync 	0;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB20_2;

BB20_3:
	ret;
}

	// .globl	LeakyForward
.visible .entry LeakyForward(
	.param .u32 LeakyForward_param_0,
	.param .u64 LeakyForward_param_1,
	.param .u64 LeakyForward_param_2,
	.param .f32 LeakyForward_param_3
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<5>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<8>;


	ld.param.u32 	%r6, [LeakyForward_param_0];
	ld.param.u64 	%rd3, [LeakyForward_param_1];
	ld.param.u64 	%rd4, [LeakyForward_param_2];
	ld.param.f32 	%f1, [LeakyForward_param_3];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB21_3;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd3;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB21_2:
	mul.wide.s32 	%rd5, %r10, 4;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f2, [%rd6];
	setp.gt.f32	%p2, %f2, 0f00000000;
	add.s64 	%rd7, %rd1, %rd5;
	mul.f32 	%f3, %f2, %f1;
	selp.f32	%f4, %f2, %f3, %p2;
	st.global.f32 	[%rd7], %f4;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB21_2;

BB21_3:
	ret;
}

	// .globl	LeakyBackward
.visible .entry LeakyBackward(
	.param .u32 LeakyBackward_param_0,
	.param .u64 LeakyBackward_param_1,
	.param .u64 LeakyBackward_param_2,
	.param .u64 LeakyBackward_param_3,
	.param .f32 LeakyBackward_param_4
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<11>;


	ld.param.u32 	%r6, [LeakyBackward_param_0];
	ld.param.u64 	%rd4, [LeakyBackward_param_1];
	ld.param.u64 	%rd5, [LeakyBackward_param_2];
	ld.param.u64 	%rd6, [LeakyBackward_param_3];
	ld.param.f32 	%f1, [LeakyBackward_param_4];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r10, %r1, %r7, %r8;
	setp.ge.s32	%p1, %r10, %r6;
	@%p1 bra 	BB22_3;

	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd4;
	mov.u32 	%r9, %nctaid.x;
	mul.lo.s32 	%r3, %r9, %r1;

BB22_2:
	mul.wide.s32 	%rd7, %r10, 4;
	add.s64 	%rd8, %rd3, %rd7;
	ld.global.f32 	%f2, [%rd8];
	setp.gt.f32	%p2, %f2, 0f00000000;
	add.s64 	%rd9, %rd2, %rd7;
	add.s64 	%rd10, %rd1, %rd7;
	ld.global.f32 	%f3, [%rd9];
	mul.f32 	%f4, %f3, %f1;
	selp.f32	%f5, %f3, %f4, %p2;
	st.global.f32 	[%rd10], %f5;
	add.s32 	%r10, %r3, %r10;
	setp.lt.s32	%p3, %r10, %r6;
	@%p3 bra 	BB22_2;

BB22_3:
	ret;
}

	// .globl	MSELoss
.visible .entry MSELoss(
	.param .u32 MSELoss_param_0,
	.param .u64 MSELoss_param_1,
	.param .u64 MSELoss_param_2,
	.param .u64 MSELoss_param_3,
	.param .u64 MSELoss_param_4,
	.param .f32 MSELoss_param_5,
	.param .f32 MSELoss_param_6
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<7>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u32 	%r6, [MSELoss_param_0];
	ld.param.u64 	%rd5, [MSELoss_param_1];
	ld.param.u64 	%rd6, [MSELoss_param_2];
	ld.param.u64 	%rd7, [MSELoss_param_3];
	ld.param.u64 	%rd8, [MSELoss_param_4];
	cvta.to.global.u64 	%rd1, %rd8;
	mov.u32 	%r7, 0;
	st.global.u32 	[%rd1], %r7;
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r11, %r1, %r8, %r9;
	setp.ge.s32	%p1, %r11, %r6;
	@%p1 bra 	BB23_3;

	cvta.to.global.u64 	%rd2, %rd5;
	cvta.to.global.u64 	%rd3, %rd6;
	cvta.to.global.u64 	%rd4, %rd7;
	mov.u32 	%r10, %nctaid.x;
	mul.lo.s32 	%r3, %r10, %r1;

BB23_2:
	mul.wide.s32 	%rd9, %r11, 4;
	add.s64 	%rd10, %rd4, %rd9;
	add.s64 	%rd11, %rd3, %rd9;
	ld.global.f32 	%f1, [%rd11];
	ld.global.f32 	%f2, [%rd10];
	sub.f32 	%f3, %f2, %f1;
	add.s64 	%rd12, %rd2, %rd9;
	st.global.f32 	[%rd12], %f3;
	mul.f32 	%f4, %f3, %f3;
	mul.f32 	%f5, %f4, 0f3F000000;
	atom.global.add.f32 	%f6, [%rd1], %f5;
	add.s32 	%r11, %r3, %r11;
	setp.lt.s32	%p2, %r11, %r6;
	@%p2 bra 	BB23_2;

BB23_3:
	ret;
}

	// .globl	MSELossbyBatches
.visible .entry MSELossbyBatches(
	.param .u32 MSELossbyBatches_param_0,
	.param .u32 MSELossbyBatches_param_1,
	.param .u64 MSELossbyBatches_param_2,
	.param .u64 MSELossbyBatches_param_3,
	.param .u64 MSELossbyBatches_param_4,
	.param .u64 MSELossbyBatches_param_5
)
{
	.reg .pred 	%p<5>;
	.reg .f32 	%f<7>;
	.reg .b32 	%r<23>;
	.reg .b64 	%rd<15>;


	ld.param.u32 	%r11, [MSELossbyBatches_param_0];
	ld.param.u32 	%r12, [MSELossbyBatches_param_1];
	ld.param.u64 	%rd5, [MSELossbyBatches_param_2];
	ld.param.u64 	%rd6, [MSELossbyBatches_param_3];
	ld.param.u64 	%rd7, [MSELossbyBatches_param_4];
	ld.param.u64 	%rd8, [MSELossbyBatches_param_5];
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r13, %ctaid.x;
	mov.u32 	%r14, %tid.x;
	mad.lo.s32 	%r21, %r1, %r13, %r14;
	setp.ge.s32	%p1, %r21, %r11;
	@%p1 bra 	BB24_6;

	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd7;
	mov.u32 	%r15, %ctaid.y;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %tid.y;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	mov.u32 	%r18, %nctaid.x;
	mul.lo.s32 	%r4, %r18, %r1;
	mov.u32 	%r19, %nctaid.y;
	mul.lo.s32 	%r5, %r19, %r16;
	cvta.to.global.u64 	%rd9, %rd8;

BB24_2:
	setp.ge.s32	%p2, %r3, %r12;
	@%p2 bra 	BB24_5;

	mul.wide.s32 	%rd10, %r21, 4;
	add.s64 	%rd4, %rd9, %rd10;
	mul.lo.s32 	%r7, %r21, %r12;
	mov.u32 	%r22, %r3;

BB24_4:
	add.s32 	%r20, %r22, %r7;
	mul.wide.s32 	%rd11, %r20, 4;
	add.s64 	%rd12, %rd3, %rd11;
	add.s64 	%rd13, %rd2, %rd11;
	ld.global.f32 	%f1, [%rd13];
	ld.global.f32 	%f2, [%rd12];
	sub.f32 	%f3, %f2, %f1;
	add.s64 	%rd14, %rd1, %rd11;
	st.global.f32 	[%rd14], %f3;
	mul.f32 	%f4, %f3, %f3;
	mul.f32 	%f5, %f4, 0f3F000000;
	atom.global.add.f32 	%f6, [%rd4], %f5;
	add.s32 	%r22, %r5, %r22;
	setp.lt.s32	%p3, %r22, %r12;
	@%p3 bra 	BB24_4;

BB24_5:
	add.s32 	%r21, %r4, %r21;
	setp.lt.s32	%p4, %r21, %r11;
	@%p4 bra 	BB24_2;

BB24_6:
	ret;
}

	// .globl	ConcatForwardNHWCEX
.visible .entry ConcatForwardNHWCEX(
	.param .u32 ConcatForwardNHWCEX_param_0,
	.param .u32 ConcatForwardNHWCEX_param_1,
	.param .u32 ConcatForwardNHWCEX_param_2,
	.param .u32 ConcatForwardNHWCEX_param_3,
	.param .u64 ConcatForwardNHWCEX_param_4,
	.param .u64 ConcatForwardNHWCEX_param_5,
	.param .u64 ConcatForwardNHWCEX_param_6,
	.param .u32 ConcatForwardNHWCEX_param_7,
	.param .u64 ConcatForwardNHWCEX_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<58>;
	.reg .b64 	%rd<24>;


	ld.param.u32 	%r26, [ConcatForwardNHWCEX_param_0];
	ld.param.u32 	%r27, [ConcatForwardNHWCEX_param_1];
	ld.param.u32 	%r28, [ConcatForwardNHWCEX_param_2];
	ld.param.u32 	%r29, [ConcatForwardNHWCEX_param_3];
	ld.param.u64 	%rd13, [ConcatForwardNHWCEX_param_4];
	ld.param.u64 	%rd14, [ConcatForwardNHWCEX_param_5];
	ld.param.u64 	%rd15, [ConcatForwardNHWCEX_param_6];
	ld.param.u32 	%r30, [ConcatForwardNHWCEX_param_7];
	ld.param.u64 	%rd16, [ConcatForwardNHWCEX_param_8];
	setp.lt.s32	%p1, %r28, 1;
	@%p1 bra 	BB25_14;

	cvta.to.global.u64 	%rd1, %rd16;
	cvta.to.global.u64 	%rd2, %rd14;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd15;
	mov.u32 	%r32, %ctaid.x;
	mov.u32 	%r33, %ntid.x;
	mov.u32 	%r34, %tid.x;
	mad.lo.s32 	%r1, %r33, %r32, %r34;
	mov.u32 	%r35, %ntid.y;
	mov.u32 	%r36, %ctaid.y;
	mov.u32 	%r37, %tid.y;
	mad.lo.s32 	%r2, %r35, %r36, %r37;
	mov.u32 	%r38, %nctaid.x;
	mul.lo.s32 	%r3, %r38, %r33;
	mov.u32 	%r39, %nctaid.y;
	mul.lo.s32 	%r4, %r39, %r35;
	mul.lo.s32 	%r5, %r29, %r28;
	mov.u32 	%r31, 0;
	mov.u32 	%r50, %r31;

BB25_2:
	setp.lt.s32	%p2, %r30, 1;
	mov.u32 	%r51, %r31;
	mov.u32 	%r52, %r31;
	@%p2 bra 	BB25_13;

BB25_3:
	cvt.s64.s32	%rd5, %r51;
	mul.wide.s32 	%rd17, %r51, 4;
	add.s64 	%rd6, %rd3, %rd17;
	setp.ge.s32	%p3, %r1, %r26;
	@%p3 bra 	BB25_12;

	add.s64 	%rd19, %rd4, %rd17;
	ld.global.u32 	%r42, [%rd19];
	mul.lo.s32 	%r9, %r50, %r42;
	add.s32 	%r10, %r5, %r52;
	mov.u32 	%r53, %r1;

BB25_5:
	setp.ge.s32	%p4, %r2, %r27;
	@%p4 bra 	BB25_11;

	ld.global.u32 	%r54, [%rd6];
	mul.lo.s32 	%r43, %r27, %r53;
	add.s32 	%r13, %r9, %r43;
	add.s32 	%r14, %r10, %r43;
	mov.u32 	%r55, %r2;

BB25_7:
	setp.lt.s32	%p5, %r54, 1;
	@%p5 bra 	BB25_10;

	mul.lo.s32 	%r45, %r54, %r55;
	add.s32 	%r46, %r13, %r45;
	mul.wide.s32 	%rd20, %r46, 4;
	add.s64 	%rd23, %rd2, %rd20;
	add.s32 	%r47, %r14, %r45;
	mul.wide.s32 	%rd21, %r47, 4;
	add.s64 	%rd22, %rd1, %rd21;
	mov.u32 	%r56, 0;

BB25_9:
	ld.global.f32 	%f1, [%rd23];
	st.global.f32 	[%rd22], %f1;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	ld.global.u32 	%r54, [%rd6];
	add.s32 	%r56, %r56, 1;
	setp.lt.s32	%p6, %r56, %r54;
	@%p6 bra 	BB25_9;

BB25_10:
	add.s32 	%r55, %r4, %r55;
	setp.lt.s32	%p7, %r55, %r27;
	@%p7 bra 	BB25_7;

BB25_11:
	add.s32 	%r53, %r3, %r53;
	setp.lt.s32	%p8, %r53, %r26;
	@%p8 bra 	BB25_5;

BB25_12:
	cvt.u32.u64	%r48, %rd5;
	ld.global.u32 	%r49, [%rd6];
	add.s32 	%r52, %r49, %r52;
	add.s32 	%r51, %r48, 1;
	setp.lt.s32	%p9, %r51, %r30;
	@%p9 bra 	BB25_3;

BB25_13:
	add.s32 	%r50, %r50, 1;
	setp.lt.s32	%p10, %r50, %r28;
	@%p10 bra 	BB25_2;

BB25_14:
	ret;
}

	// .globl	ConcatBackwardNHWCEX
.visible .entry ConcatBackwardNHWCEX(
	.param .u32 ConcatBackwardNHWCEX_param_0,
	.param .u32 ConcatBackwardNHWCEX_param_1,
	.param .u32 ConcatBackwardNHWCEX_param_2,
	.param .u32 ConcatBackwardNHWCEX_param_3,
	.param .u64 ConcatBackwardNHWCEX_param_4,
	.param .u64 ConcatBackwardNHWCEX_param_5,
	.param .u64 ConcatBackwardNHWCEX_param_6,
	.param .u32 ConcatBackwardNHWCEX_param_7,
	.param .u64 ConcatBackwardNHWCEX_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<58>;
	.reg .b64 	%rd<24>;


	ld.param.u32 	%r26, [ConcatBackwardNHWCEX_param_0];
	ld.param.u32 	%r27, [ConcatBackwardNHWCEX_param_1];
	ld.param.u32 	%r28, [ConcatBackwardNHWCEX_param_2];
	ld.param.u32 	%r29, [ConcatBackwardNHWCEX_param_3];
	ld.param.u64 	%rd13, [ConcatBackwardNHWCEX_param_4];
	ld.param.u64 	%rd14, [ConcatBackwardNHWCEX_param_5];
	ld.param.u64 	%rd15, [ConcatBackwardNHWCEX_param_6];
	ld.param.u32 	%r30, [ConcatBackwardNHWCEX_param_7];
	ld.param.u64 	%rd16, [ConcatBackwardNHWCEX_param_8];
	setp.lt.s32	%p1, %r28, 1;
	@%p1 bra 	BB26_14;

	cvta.to.global.u64 	%rd1, %rd14;
	cvta.to.global.u64 	%rd2, %rd16;
	cvta.to.global.u64 	%rd3, %rd13;
	cvta.to.global.u64 	%rd4, %rd15;
	mov.u32 	%r32, %ctaid.x;
	mov.u32 	%r33, %ntid.x;
	mov.u32 	%r34, %tid.x;
	mad.lo.s32 	%r1, %r33, %r32, %r34;
	mov.u32 	%r35, %ntid.y;
	mov.u32 	%r36, %ctaid.y;
	mov.u32 	%r37, %tid.y;
	mad.lo.s32 	%r2, %r35, %r36, %r37;
	mov.u32 	%r38, %nctaid.x;
	mul.lo.s32 	%r3, %r38, %r33;
	mov.u32 	%r39, %nctaid.y;
	mul.lo.s32 	%r4, %r39, %r35;
	mul.lo.s32 	%r5, %r29, %r28;
	mov.u32 	%r31, 0;
	mov.u32 	%r50, %r31;

BB26_2:
	setp.lt.s32	%p2, %r30, 1;
	mov.u32 	%r51, %r31;
	mov.u32 	%r52, %r31;
	@%p2 bra 	BB26_13;

BB26_3:
	cvt.s64.s32	%rd5, %r51;
	mul.wide.s32 	%rd17, %r51, 4;
	add.s64 	%rd6, %rd3, %rd17;
	setp.ge.s32	%p3, %r1, %r26;
	@%p3 bra 	BB26_12;

	add.s64 	%rd19, %rd4, %rd17;
	ld.global.u32 	%r42, [%rd19];
	add.s32 	%r9, %r5, %r52;
	mul.lo.s32 	%r10, %r50, %r42;
	mov.u32 	%r53, %r1;

BB26_5:
	setp.ge.s32	%p4, %r2, %r27;
	@%p4 bra 	BB26_11;

	ld.global.u32 	%r54, [%rd6];
	mul.lo.s32 	%r43, %r27, %r53;
	add.s32 	%r13, %r9, %r43;
	add.s32 	%r14, %r10, %r43;
	mov.u32 	%r55, %r2;

BB26_7:
	setp.lt.s32	%p5, %r54, 1;
	@%p5 bra 	BB26_10;

	mul.lo.s32 	%r45, %r54, %r55;
	add.s32 	%r46, %r13, %r45;
	mul.wide.s32 	%rd20, %r46, 4;
	add.s64 	%rd23, %rd2, %rd20;
	add.s32 	%r47, %r14, %r45;
	mul.wide.s32 	%rd21, %r47, 4;
	add.s64 	%rd22, %rd1, %rd21;
	mov.u32 	%r56, 0;

BB26_9:
	ld.global.f32 	%f1, [%rd23];
	st.global.f32 	[%rd22], %f1;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	ld.global.u32 	%r54, [%rd6];
	add.s32 	%r56, %r56, 1;
	setp.lt.s32	%p6, %r56, %r54;
	@%p6 bra 	BB26_9;

BB26_10:
	add.s32 	%r55, %r4, %r55;
	setp.lt.s32	%p7, %r55, %r27;
	@%p7 bra 	BB26_7;

BB26_11:
	add.s32 	%r53, %r3, %r53;
	setp.lt.s32	%p8, %r53, %r26;
	@%p8 bra 	BB26_5;

BB26_12:
	cvt.u32.u64	%r48, %rd5;
	ld.global.u32 	%r49, [%rd6];
	add.s32 	%r52, %r49, %r52;
	add.s32 	%r51, %r48, 1;
	setp.lt.s32	%p9, %r51, %r30;
	@%p9 bra 	BB26_3;

BB26_13:
	add.s32 	%r50, %r50, 1;
	setp.lt.s32	%p10, %r50, %r28;
	@%p10 bra 	BB26_2;

BB26_14:
	ret;
}

	// .globl	ConcatForwardNCHWEX
.visible .entry ConcatForwardNCHWEX(
	.param .u32 ConcatForwardNCHWEX_param_0,
	.param .u32 ConcatForwardNCHWEX_param_1,
	.param .u32 ConcatForwardNCHWEX_param_2,
	.param .u64 ConcatForwardNCHWEX_param_3,
	.param .u64 ConcatForwardNCHWEX_param_4,
	.param .u64 ConcatForwardNCHWEX_param_5,
	.param .u32 ConcatForwardNCHWEX_param_6,
	.param .u64 ConcatForwardNCHWEX_param_7
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<16>;


	ld.param.u32 	%r31, [ConcatForwardNCHWEX_param_0];
	ld.param.u32 	%r32, [ConcatForwardNCHWEX_param_1];
	ld.param.u32 	%r33, [ConcatForwardNCHWEX_param_2];
	ld.param.u64 	%rd7, [ConcatForwardNCHWEX_param_3];
	ld.param.u64 	%rd8, [ConcatForwardNCHWEX_param_4];
	ld.param.u64 	%rd9, [ConcatForwardNCHWEX_param_5];
	ld.param.u32 	%r34, [ConcatForwardNCHWEX_param_6];
	ld.param.u64 	%rd10, [ConcatForwardNCHWEX_param_7];
	setp.lt.s32	%p1, %r32, 1;
	@%p1 bra 	BB27_13;

	cvta.to.global.u64 	%rd1, %rd10;
	cvta.to.global.u64 	%rd2, %rd8;
	cvta.to.global.u64 	%rd3, %rd7;
	cvta.to.global.u64 	%rd4, %rd9;
	mov.u32 	%r36, %ctaid.x;
	mov.u32 	%r37, %ntid.x;
	mov.u32 	%r38, %tid.x;
	mad.lo.s32 	%r1, %r37, %r36, %r38;
	mov.u32 	%r39, %nctaid.x;
	mul.lo.s32 	%r2, %r39, %r37;
	mad.lo.s32 	%r4, %r33, %r32, %r1;
	mad.lo.s32 	%r5, %r36, %r37, %r38;
	mov.u32 	%r35, 0;
	mov.u32 	%r44, %r35;

BB27_2:
	setp.lt.s32	%p2, %r34, 1;
	mov.u32 	%r45, %r35;
	mov.u32 	%r46, %r35;
	@%p2 bra 	BB27_12;

BB27_3:
	mul.wide.s32 	%rd11, %r45, 4;
	add.s64 	%rd5, %rd4, %rd11;
	ld.global.u32 	%r53, [%rd5];
	add.s64 	%rd6, %rd3, %rd11;
	ld.global.u32 	%r52, [%rd6];
	setp.lt.s32	%p3, %r52, 1;
	@%p3 bra 	BB27_11;

	mad.lo.s32 	%r11, %r44, %r53, %r1;
	add.s32 	%r12, %r4, %r46;
	mov.u32 	%r48, 0;

BB27_5:
	setp.ge.s32	%p4, %r1, %r31;
	@%p4 bra 	BB27_9;

	mul.lo.s32 	%r43, %r31, %r48;
	add.s32 	%r51, %r11, %r43;
	add.s32 	%r50, %r12, %r43;
	mov.u32 	%r49, %r5;

BB27_7:
	mul.wide.s32 	%rd12, %r51, 4;
	add.s64 	%rd13, %rd2, %rd12;
	ld.global.f32 	%f1, [%rd13];
	mul.wide.s32 	%rd14, %r50, 4;
	add.s64 	%rd15, %rd1, %rd14;
	st.global.f32 	[%rd15], %f1;
	add.s32 	%r51, %r51, %r2;
	add.s32 	%r50, %r50, %r2;
	add.s32 	%r49, %r49, %r2;
	setp.lt.s32	%p5, %r49, %r31;
	@%p5 bra 	BB27_7;

	ld.global.u32 	%r52, [%rd6];

BB27_9:
	add.s32 	%r48, %r48, 1;
	setp.lt.s32	%p6, %r48, %r52;
	@%p6 bra 	BB27_5;

	ld.global.u32 	%r53, [%rd5];

BB27_11:
	mad.lo.s32 	%r46, %r53, %r32, %r46;
	add.s32 	%r45, %r45, 1;
	setp.lt.s32	%p7, %r45, %r34;
	@%p7 bra 	BB27_3;

BB27_12:
	add.s32 	%r44, %r44, 1;
	setp.lt.s32	%p8, %r44, %r32;
	@%p8 bra 	BB27_2;

BB27_13:
	ret;
}

	// .globl	ConcatBackwardNCHWEX
.visible .entry ConcatBackwardNCHWEX(
	.param .u32 ConcatBackwardNCHWEX_param_0,
	.param .u32 ConcatBackwardNCHWEX_param_1,
	.param .u32 ConcatBackwardNCHWEX_param_2,
	.param .u64 ConcatBackwardNCHWEX_param_3,
	.param .u64 ConcatBackwardNCHWEX_param_4,
	.param .u64 ConcatBackwardNCHWEX_param_5,
	.param .u32 ConcatBackwardNCHWEX_param_6,
	.param .u64 ConcatBackwardNCHWEX_param_7
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<16>;


	ld.param.u32 	%r31, [ConcatBackwardNCHWEX_param_0];
	ld.param.u32 	%r32, [ConcatBackwardNCHWEX_param_1];
	ld.param.u32 	%r33, [ConcatBackwardNCHWEX_param_2];
	ld.param.u64 	%rd7, [ConcatBackwardNCHWEX_param_3];
	ld.param.u64 	%rd8, [ConcatBackwardNCHWEX_param_4];
	ld.param.u64 	%rd9, [ConcatBackwardNCHWEX_param_5];
	ld.param.u32 	%r34, [ConcatBackwardNCHWEX_param_6];
	ld.param.u64 	%rd10, [ConcatBackwardNCHWEX_param_7];
	setp.lt.s32	%p1, %r32, 1;
	@%p1 bra 	BB28_13;

	cvta.to.global.u64 	%rd1, %rd8;
	cvta.to.global.u64 	%rd2, %rd10;
	cvta.to.global.u64 	%rd3, %rd7;
	cvta.to.global.u64 	%rd4, %rd9;
	mov.u32 	%r36, %ctaid.x;
	mov.u32 	%r37, %ntid.x;
	mov.u32 	%r38, %tid.x;
	mad.lo.s32 	%r1, %r37, %r36, %r38;
	mov.u32 	%r39, %nctaid.x;
	mul.lo.s32 	%r2, %r39, %r37;
	mad.lo.s32 	%r3, %r33, %r32, %r1;
	mad.lo.s32 	%r5, %r36, %r37, %r38;
	mov.u32 	%r35, 0;
	mov.u32 	%r44, %r35;

BB28_2:
	setp.lt.s32	%p2, %r34, 1;
	mov.u32 	%r45, %r35;
	mov.u32 	%r46, %r35;
	@%p2 bra 	BB28_12;

BB28_3:
	mul.wide.s32 	%rd11, %r45, 4;
	add.s64 	%rd5, %rd4, %rd11;
	ld.global.u32 	%r53, [%rd5];
	add.s64 	%rd6, %rd3, %rd11;
	ld.global.u32 	%r52, [%rd6];
	setp.lt.s32	%p3, %r52, 1;
	@%p3 bra 	BB28_11;

	add.s32 	%r11, %r3, %r46;
	mad.lo.s32 	%r12, %r44, %r53, %r1;
	mov.u32 	%r48, 0;

BB28_5:
	setp.ge.s32	%p4, %r1, %r31;
	@%p4 bra 	BB28_9;

	mul.lo.s32 	%r43, %r31, %r48;
	add.s32 	%r51, %r11, %r43;
	add.s32 	%r50, %r12, %r43;
	mov.u32 	%r49, %r5;

BB28_7:
	mul.wide.s32 	%rd12, %r51, 4;
	add.s64 	%rd13, %rd2, %rd12;
	ld.global.f32 	%f1, [%rd13];
	mul.wide.s32 	%rd14, %r50, 4;
	add.s64 	%rd15, %rd1, %rd14;
	st.global.f32 	[%rd15], %f1;
	add.s32 	%r51, %r51, %r2;
	add.s32 	%r50, %r50, %r2;
	add.s32 	%r49, %r49, %r2;
	setp.lt.s32	%p5, %r49, %r31;
	@%p5 bra 	BB28_7;

	ld.global.u32 	%r52, [%rd6];

BB28_9:
	add.s32 	%r48, %r48, 1;
	setp.lt.s32	%p6, %r48, %r52;
	@%p6 bra 	BB28_5;

	ld.global.u32 	%r53, [%rd5];

BB28_11:
	mad.lo.s32 	%r46, %r53, %r32, %r46;
	add.s32 	%r45, %r45, 1;
	setp.lt.s32	%p7, %r45, %r34;
	@%p7 bra 	BB28_3;

BB28_12:
	add.s32 	%r44, %r44, 1;
	setp.lt.s32	%p8, %r44, %r32;
	@%p8 bra 	BB28_2;

BB28_13:
	ret;
}

	// .globl	ConcatForwardNCHW
.visible .entry ConcatForwardNCHW(
	.param .u32 ConcatForwardNCHW_param_0,
	.param .u32 ConcatForwardNCHW_param_1,
	.param .u32 ConcatForwardNCHW_param_2,
	.param .u32 ConcatForwardNCHW_param_3,
	.param .u64 ConcatForwardNCHW_param_4,
	.param .u32 ConcatForwardNCHW_param_5,
	.param .u32 ConcatForwardNCHW_param_6,
	.param .u64 ConcatForwardNCHW_param_7,
	.param .u64 ConcatForwardNCHW_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<73>;
	.reg .b64 	%rd<16>;


	ld.param.u32 	%r31, [ConcatForwardNCHW_param_0];
	ld.param.u32 	%r32, [ConcatForwardNCHW_param_1];
	ld.param.u32 	%r33, [ConcatForwardNCHW_param_2];
	ld.param.u32 	%r34, [ConcatForwardNCHW_param_3];
	ld.param.u64 	%rd3, [ConcatForwardNCHW_param_4];
	ld.param.u32 	%r35, [ConcatForwardNCHW_param_5];
	ld.param.u32 	%r36, [ConcatForwardNCHW_param_6];
	ld.param.u64 	%rd4, [ConcatForwardNCHW_param_7];
	ld.param.u64 	%rd5, [ConcatForwardNCHW_param_8];
	setp.lt.s32	%p1, %r32, 1;
	@%p1 bra 	BB29_15;

	cvta.to.global.u64 	%rd1, %rd3;
	cvta.to.global.u64 	%rd2, %rd4;
	mov.u32 	%r38, %ctaid.x;
	mov.u32 	%r39, %ntid.x;
	mov.u32 	%r40, %tid.x;
	mad.lo.s32 	%r1, %r39, %r38, %r40;
	add.s32 	%r41, %r36, %r34;
	mad.lo.s32 	%r2, %r32, %r41, %r1;
	mov.u32 	%r42, %nctaid.x;
	mul.lo.s32 	%r3, %r42, %r39;
	add.s32 	%r4, %r2, %r34;
	mov.u32 	%r64, 0;

BB29_2:
	setp.lt.s32	%p2, %r33, 1;
	@%p2 bra 	BB29_8;

	mad.lo.s32 	%r6, %r34, %r64, %r1;
	mov.u32 	%r65, 0;

BB29_4:
	setp.ge.s32	%p3, %r1, %r31;
	@%p3 bra 	BB29_7;

	mul.lo.s32 	%r48, %r31, %r65;
	add.s32 	%r68, %r6, %r48;
	add.s32 	%r67, %r2, %r48;
	mad.lo.s32 	%r66, %r38, %r39, %r40;

BB29_6:
	mul.wide.s32 	%rd6, %r68, 4;
	add.s64 	%rd7, %rd1, %rd6;
	ld.global.f32 	%f1, [%rd7];
	cvta.to.global.u64 	%rd8, %rd5;
	mul.wide.s32 	%rd9, %r67, 4;
	add.s64 	%rd10, %rd8, %rd9;
	st.global.f32 	[%rd10], %f1;
	add.s32 	%r68, %r68, %r3;
	add.s32 	%r67, %r67, %r3;
	add.s32 	%r66, %r66, %r3;
	setp.lt.s32	%p4, %r66, %r31;
	@%p4 bra 	BB29_6;

BB29_7:
	add.s32 	%r65, %r65, 1;
	setp.lt.s32	%p5, %r65, %r33;
	@%p5 bra 	BB29_4;

BB29_8:
	setp.lt.s32	%p6, %r35, 1;
	@%p6 bra 	BB29_14;

	mad.lo.s32 	%r18, %r36, %r64, %r1;
	mov.u32 	%r69, 0;

BB29_10:
	setp.ge.s32	%p7, %r1, %r31;
	@%p7 bra 	BB29_13;

	mul.lo.s32 	%r60, %r31, %r69;
	add.s32 	%r72, %r18, %r60;
	add.s32 	%r71, %r4, %r60;
	mad.lo.s32 	%r70, %r38, %r39, %r40;

BB29_12:
	mul.wide.s32 	%rd11, %r72, 4;
	add.s64 	%rd12, %rd2, %rd11;
	ld.global.f32 	%f2, [%rd12];
	cvta.to.global.u64 	%rd13, %rd5;
	mul.wide.s32 	%rd14, %r71, 4;
	add.s64 	%rd15, %rd13, %rd14;
	st.global.f32 	[%rd15], %f2;
	add.s32 	%r72, %r72, %r3;
	add.s32 	%r71, %r71, %r3;
	add.s32 	%r70, %r70, %r3;
	setp.lt.s32	%p8, %r70, %r31;
	@%p8 bra 	BB29_12;

BB29_13:
	add.s32 	%r69, %r69, 1;
	setp.lt.s32	%p9, %r69, %r35;
	@%p9 bra 	BB29_10;

BB29_14:
	add.s32 	%r64, %r64, 1;
	setp.lt.s32	%p10, %r64, %r32;
	@%p10 bra 	BB29_2;

BB29_15:
	ret;
}

	// .globl	ConcatBackwardNCHW
.visible .entry ConcatBackwardNCHW(
	.param .u32 ConcatBackwardNCHW_param_0,
	.param .u32 ConcatBackwardNCHW_param_1,
	.param .u32 ConcatBackwardNCHW_param_2,
	.param .u32 ConcatBackwardNCHW_param_3,
	.param .u64 ConcatBackwardNCHW_param_4,
	.param .u32 ConcatBackwardNCHW_param_5,
	.param .u32 ConcatBackwardNCHW_param_6,
	.param .u64 ConcatBackwardNCHW_param_7,
	.param .u64 ConcatBackwardNCHW_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<71>;
	.reg .b64 	%rd<15>;


	ld.param.u32 	%r32, [ConcatBackwardNCHW_param_0];
	ld.param.u32 	%r33, [ConcatBackwardNCHW_param_1];
	ld.param.u32 	%r34, [ConcatBackwardNCHW_param_2];
	ld.param.u32 	%r35, [ConcatBackwardNCHW_param_3];
	ld.param.u64 	%rd2, [ConcatBackwardNCHW_param_4];
	ld.param.u32 	%r36, [ConcatBackwardNCHW_param_5];
	ld.param.u32 	%r37, [ConcatBackwardNCHW_param_6];
	ld.param.u64 	%rd3, [ConcatBackwardNCHW_param_7];
	ld.param.u64 	%rd4, [ConcatBackwardNCHW_param_8];
	cvta.to.global.u64 	%rd1, %rd4;
	setp.lt.s32	%p1, %r33, 1;
	@%p1 bra 	BB30_15;

	mov.u32 	%r39, %ctaid.x;
	mov.u32 	%r40, %ntid.x;
	mov.u32 	%r41, %tid.x;
	mad.lo.s32 	%r1, %r40, %r39, %r41;
	mov.u32 	%r42, %nctaid.x;
	mul.lo.s32 	%r5, %r42, %r40;
	add.s32 	%r43, %r37, %r35;
	mad.lo.s32 	%r3, %r33, %r43, %r1;
	add.s32 	%r4, %r3, %r35;
	mov.u32 	%r62, 0;
	cvta.to.global.u64 	%rd7, %rd2;
	cvta.to.global.u64 	%rd12, %rd3;

BB30_2:
	setp.lt.s32	%p2, %r34, 1;
	@%p2 bra 	BB30_8;

	mad.lo.s32 	%r7, %r35, %r62, %r1;
	mov.u32 	%r63, 0;

BB30_4:
	setp.ge.s32	%p3, %r1, %r32;
	@%p3 bra 	BB30_7;

	mul.lo.s32 	%r49, %r32, %r63;
	add.s32 	%r66, %r3, %r49;
	add.s32 	%r65, %r7, %r49;
	mad.lo.s32 	%r64, %r39, %r40, %r41;

BB30_6:
	mul.wide.s32 	%rd5, %r66, 4;
	add.s64 	%rd6, %rd1, %rd5;
	ld.global.f32 	%f1, [%rd6];
	mul.wide.s32 	%rd8, %r65, 4;
	add.s64 	%rd9, %rd7, %rd8;
	st.global.f32 	[%rd9], %f1;
	add.s32 	%r66, %r66, %r5;
	add.s32 	%r65, %r65, %r5;
	add.s32 	%r64, %r64, %r5;
	setp.lt.s32	%p4, %r64, %r32;
	@%p4 bra 	BB30_6;

BB30_7:
	add.s32 	%r63, %r63, 1;
	setp.lt.s32	%p5, %r63, %r34;
	@%p5 bra 	BB30_4;

BB30_8:
	setp.lt.s32	%p6, %r36, 1;
	@%p6 bra 	BB30_14;

	mad.lo.s32 	%r19, %r37, %r62, %r1;
	mov.u32 	%r67, 0;

BB30_10:
	setp.ge.s32	%p7, %r1, %r32;
	@%p7 bra 	BB30_13;

	mul.lo.s32 	%r58, %r32, %r67;
	add.s32 	%r70, %r4, %r58;
	add.s32 	%r69, %r19, %r58;
	mad.lo.s32 	%r68, %r39, %r40, %r41;

BB30_12:
	mul.wide.s32 	%rd10, %r70, 4;
	add.s64 	%rd11, %rd1, %rd10;
	ld.global.f32 	%f2, [%rd11];
	mul.wide.s32 	%rd13, %r69, 4;
	add.s64 	%rd14, %rd12, %rd13;
	st.global.f32 	[%rd14], %f2;
	add.s32 	%r70, %r70, %r5;
	add.s32 	%r69, %r69, %r5;
	add.s32 	%r68, %r68, %r5;
	setp.lt.s32	%p8, %r68, %r32;
	@%p8 bra 	BB30_12;

BB30_13:
	add.s32 	%r67, %r67, 1;
	setp.lt.s32	%p9, %r67, %r36;
	@%p9 bra 	BB30_10;

BB30_14:
	add.s32 	%r62, %r62, 1;
	setp.lt.s32	%p10, %r62, %r33;
	@%p10 bra 	BB30_2;

BB30_15:
	ret;
}

	// .globl	ConcatForwardNCHWhalf
.visible .entry ConcatForwardNCHWhalf(
	.param .u32 ConcatForwardNCHWhalf_param_0,
	.param .u32 ConcatForwardNCHWhalf_param_1,
	.param .u32 ConcatForwardNCHWhalf_param_2,
	.param .u32 ConcatForwardNCHWhalf_param_3,
	.param .u64 ConcatForwardNCHWhalf_param_4,
	.param .u32 ConcatForwardNCHWhalf_param_5,
	.param .u32 ConcatForwardNCHWhalf_param_6,
	.param .u64 ConcatForwardNCHWhalf_param_7,
	.param .u64 ConcatForwardNCHWhalf_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .b16 	%rs<3>;
	.reg .b32 	%r<74>;
	.reg .b64 	%rd<15>;


	ld.param.u32 	%r30, [ConcatForwardNCHWhalf_param_0];
	ld.param.u32 	%r31, [ConcatForwardNCHWhalf_param_1];
	ld.param.u32 	%r32, [ConcatForwardNCHWhalf_param_2];
	ld.param.u32 	%r33, [ConcatForwardNCHWhalf_param_3];
	ld.param.u64 	%rd4, [ConcatForwardNCHWhalf_param_4];
	ld.param.u32 	%r34, [ConcatForwardNCHWhalf_param_5];
	ld.param.u32 	%r35, [ConcatForwardNCHWhalf_param_6];
	ld.param.u64 	%rd5, [ConcatForwardNCHWhalf_param_7];
	ld.param.u64 	%rd6, [ConcatForwardNCHWhalf_param_8];
	cvta.to.global.u64 	%rd1, %rd6;
	setp.lt.s32	%p1, %r31, 1;
	@%p1 bra 	BB31_15;

	cvta.to.global.u64 	%rd2, %rd4;
	cvta.to.global.u64 	%rd3, %rd5;
	mov.u32 	%r37, %ctaid.x;
	mov.u32 	%r38, %ntid.x;
	mov.u32 	%r39, %tid.x;
	mad.lo.s32 	%r1, %r38, %r37, %r39;
	add.s32 	%r40, %r35, %r33;
	mad.lo.s32 	%r2, %r31, %r40, %r1;
	add.s32 	%r3, %r2, %r33;
	mov.u32 	%r65, 0;

BB31_2:
	setp.lt.s32	%p2, %r32, 1;
	@%p2 bra 	BB31_8;

	mad.lo.s32 	%r5, %r33, %r65, %r1;
	mov.u32 	%r66, 0;

BB31_4:
	setp.ge.s32	%p3, %r1, %r30;
	@%p3 bra 	BB31_7;

	mul.lo.s32 	%r46, %r30, %r66;
	add.s32 	%r69, %r2, %r46;
	add.s32 	%r68, %r5, %r46;
	mad.lo.s32 	%r67, %r37, %r38, %r39;

BB31_6:
	mul.wide.s32 	%rd7, %r69, 2;
	add.s64 	%rd8, %rd1, %rd7;
	mul.wide.s32 	%rd9, %r68, 2;
	add.s64 	%rd10, %rd2, %rd9;
	ld.global.u16 	%rs1, [%rd10];
	st.global.u16 	[%rd8], %rs1;
	mov.u32 	%r51, %nctaid.x;
	mul.lo.s32 	%r52, %r51, %r38;
	add.s32 	%r69, %r69, %r52;
	add.s32 	%r68, %r68, %r52;
	add.s32 	%r67, %r67, %r52;
	setp.lt.s32	%p4, %r67, %r30;
	@%p4 bra 	BB31_6;

BB31_7:
	add.s32 	%r66, %r66, 1;
	setp.lt.s32	%p5, %r66, %r32;
	@%p5 bra 	BB31_4;

BB31_8:
	setp.lt.s32	%p6, %r34, 1;
	@%p6 bra 	BB31_14;

	mad.lo.s32 	%r17, %r35, %r65, %r1;
	mov.u32 	%r70, 0;

BB31_10:
	setp.ge.s32	%p7, %r1, %r30;
	@%p7 bra 	BB31_13;

	mul.lo.s32 	%r58, %r30, %r70;
	add.s32 	%r73, %r3, %r58;
	add.s32 	%r72, %r17, %r58;
	mad.lo.s32 	%r71, %r37, %r38, %r39;

BB31_12:
	mul.wide.s32 	%rd11, %r73, 2;
	add.s64 	%rd12, %rd1, %rd11;
	mul.wide.s32 	%rd13, %r72, 2;
	add.s64 	%rd14, %rd3, %rd13;
	ld.global.u16 	%rs2, [%rd14];
	st.global.u16 	[%rd12], %rs2;
	mov.u32 	%r63, %nctaid.x;
	mul.lo.s32 	%r64, %r63, %r38;
	add.s32 	%r73, %r73, %r64;
	add.s32 	%r72, %r72, %r64;
	add.s32 	%r71, %r71, %r64;
	setp.lt.s32	%p8, %r71, %r30;
	@%p8 bra 	BB31_12;

BB31_13:
	add.s32 	%r70, %r70, 1;
	setp.lt.s32	%p9, %r70, %r34;
	@%p9 bra 	BB31_10;

BB31_14:
	add.s32 	%r65, %r65, 1;
	setp.lt.s32	%p10, %r65, %r31;
	@%p10 bra 	BB31_2;

BB31_15:
	ret;
}

	// .globl	ConcatBackwardNCHWhalf
.visible .entry ConcatBackwardNCHWhalf(
	.param .u32 ConcatBackwardNCHWhalf_param_0,
	.param .u32 ConcatBackwardNCHWhalf_param_1,
	.param .u32 ConcatBackwardNCHWhalf_param_2,
	.param .u32 ConcatBackwardNCHWhalf_param_3,
	.param .u64 ConcatBackwardNCHWhalf_param_4,
	.param .u32 ConcatBackwardNCHWhalf_param_5,
	.param .u32 ConcatBackwardNCHWhalf_param_6,
	.param .u64 ConcatBackwardNCHWhalf_param_7,
	.param .u64 ConcatBackwardNCHWhalf_param_8
)
{
	.reg .pred 	%p<11>;
	.reg .b16 	%rs<3>;
	.reg .b32 	%r<74>;
	.reg .b64 	%rd<15>;


	ld.param.u32 	%r30, [ConcatBackwardNCHWhalf_param_0];
	ld.param.u32 	%r31, [ConcatBackwardNCHWhalf_param_1];
	ld.param.u32 	%r32, [ConcatBackwardNCHWhalf_param_2];
	ld.param.u32 	%r33, [ConcatBackwardNCHWhalf_param_3];
	ld.param.u64 	%rd4, [ConcatBackwardNCHWhalf_param_4];
	ld.param.u32 	%r34, [ConcatBackwardNCHWhalf_param_5];
	ld.param.u32 	%r35, [ConcatBackwardNCHWhalf_param_6];
	ld.param.u64 	%rd5, [ConcatBackwardNCHWhalf_param_7];
	ld.param.u64 	%rd6, [ConcatBackwardNCHWhalf_param_8];
	cvta.to.global.u64 	%rd1, %rd6;
	setp.lt.s32	%p1, %r31, 1;
	@%p1 bra 	BB32_15;

	cvta.to.global.u64 	%rd2, %rd4;
	cvta.to.global.u64 	%rd3, %rd5;
	mov.u32 	%r37, %ctaid.x;
	mov.u32 	%r38, %ntid.x;
	mov.u32 	%r39, %tid.x;
	mad.lo.s32 	%r1, %r38, %r37, %r39;
	add.s32 	%r40, %r35, %r33;
	mad.lo.s32 	%r2, %r31, %r40, %r1;
	add.s32 	%r3, %r2, %r33;
	mov.u32 	%r65, 0;

BB32_2:
	setp.lt.s32	%p2, %r32, 1;
	@%p2 bra 	BB32_8;

	mad.lo.s32 	%r5, %r33, %r65, %r1;
	mov.u32 	%r66, 0;

BB32_4:
	setp.ge.s32	%p3, %r1, %r30;
	@%p3 bra 	BB32_7;

	mul.lo.s32 	%r46, %r30, %r66;
	add.s32 	%r69, %r5, %r46;
	add.s32 	%r68, %r2, %r46;
	mad.lo.s32 	%r67, %r37, %r38, %r39;

BB32_6:
	mul.wide.s32 	%rd7, %r69, 2;
	add.s64 	%rd8, %rd2, %rd7;
	mul.wide.s32 	%rd9, %r68, 2;
	add.s64 	%rd10, %rd1, %rd9;
	ld.global.u16 	%rs1, [%rd10];
	st.global.u16 	[%rd8], %rs1;
	mov.u32 	%r51, %nctaid.x;
	mul.lo.s32 	%r52, %r51, %r38;
	add.s32 	%r69, %r69, %r52;
	add.s32 	%r68, %r68, %r52;
	add.s32 	%r67, %r67, %r52;
	setp.lt.s32	%p4, %r67, %r30;
	@%p4 bra 	BB32_6;

BB32_7:
	add.s32 	%r66, %r66, 1;
	setp.lt.s32	%p5, %r66, %r32;
	@%p5 bra 	BB32_4;

BB32_8:
	setp.lt.s32	%p6, %r34, 1;
	@%p6 bra 	BB32_14;

	mad.lo.s32 	%r17, %r35, %r65, %r1;
	mov.u32 	%r70, 0;

BB32_10:
	setp.ge.s32	%p7, %r1, %r30;
	@%p7 bra 	BB32_13;

	mul.lo.s32 	%r58, %r30, %r70;
	add.s32 	%r73, %r17, %r58;
	add.s32 	%r72, %r3, %r58;
	mad.lo.s32 	%r71, %r37, %r38, %r39;

BB32_12:
	mul.wide.s32 	%rd11, %r73, 2;
	add.s64 	%rd12, %rd3, %rd11;
	mul.wide.s32 	%rd13, %r72, 2;
	add.s64 	%rd14, %rd1, %rd13;
	ld.global.u16 	%rs2, [%rd14];
	st.global.u16 	[%rd12], %rs2;
	mov.u32 	%r63, %nctaid.x;
	mul.lo.s32 	%r64, %r63, %r38;
	add.s32 	%r73, %r73, %r64;
	add.s32 	%r72, %r72, %r64;
	add.s32 	%r71, %r71, %r64;
	setp.lt.s32	%p8, %r71, %r30;
	@%p8 bra 	BB32_12;

BB32_13:
	add.s32 	%r70, %r70, 1;
	setp.lt.s32	%p9, %r70, %r34;
	@%p9 bra 	BB32_10;

BB32_14:
	add.s32 	%r65, %r65, 1;
	setp.lt.s32	%p10, %r65, %r31;
	@%p10 bra 	BB32_2;

BB32_15:
	ret;
}

	// .globl	MakePlanarImageBatchesUint8
.visible .entry MakePlanarImageBatchesUint8(
	.param .u32 MakePlanarImageBatchesUint8_param_0,
	.param .u32 MakePlanarImageBatchesUint8_param_1,
	.param .u32 MakePlanarImageBatchesUint8_param_2,
	.param .u64 MakePlanarImageBatchesUint8_param_3,
	.param .u64 MakePlanarImageBatchesUint8_param_4
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<34>;
	.reg .b64 	%rd<9>;


	ld.param.u32 	%r19, [MakePlanarImageBatchesUint8_param_0];
	ld.param.u32 	%r20, [MakePlanarImageBatchesUint8_param_1];
	ld.param.u32 	%r21, [MakePlanarImageBatchesUint8_param_2];
	ld.param.u64 	%rd3, [MakePlanarImageBatchesUint8_param_3];
	ld.param.u64 	%rd4, [MakePlanarImageBatchesUint8_param_4];
	setp.lt.s32	%p1, %r20, 1;
	@%p1 bra 	BB33_9;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd3;
	mov.u32 	%r23, %ctaid.x;
	mov.u32 	%r24, %ntid.x;
	mov.u32 	%r25, %tid.x;
	mad.lo.s32 	%r1, %r24, %r23, %r25;
	mov.u32 	%r26, %nctaid.x;
	mul.lo.s32 	%r2, %r26, %r24;
	mad.lo.s32 	%r5, %r23, %r24, %r25;
	mov.u32 	%r29, 0;

BB33_2:
	setp.lt.s32	%p2, %r21, 1;
	@%p2 bra 	BB33_8;

	mul.lo.s32 	%r7, %r21, %r29;
	mov.u32 	%r30, 0;

BB33_4:
	setp.ge.s32	%p3, %r1, %r19;
	@%p3 bra 	BB33_7;

	add.s32 	%r28, %r7, %r30;
	mad.lo.s32 	%r33, %r19, %r28, %r1;
	mad.lo.s32 	%r32, %r19, %r30, %r1;
	mov.u32 	%r31, %r5;

BB33_6:
	mul.wide.s32 	%rd5, %r32, 4;
	add.s64 	%rd6, %rd2, %rd5;
	ld.global.f32 	%f1, [%rd6];
	mul.wide.s32 	%rd7, %r33, 4;
	add.s64 	%rd8, %rd1, %rd7;
	st.global.f32 	[%rd8], %f1;
	add.s32 	%r33, %r33, %r2;
	add.s32 	%r32, %r32, %r2;
	add.s32 	%r31, %r31, %r2;
	setp.lt.s32	%p4, %r31, %r19;
	@%p4 bra 	BB33_6;

BB33_7:
	add.s32 	%r30, %r30, 1;
	setp.lt.s32	%p5, %r30, %r21;
	@%p5 bra 	BB33_4;

BB33_8:
	add.s32 	%r29, %r29, 1;
	setp.lt.s32	%p6, %r29, %r20;
	@%p6 bra 	BB33_2;

BB33_9:
	ret;
}
`
