package nppi

/*
#include <nppi_geometry_transforms.h>
#include <nppdefs.h>
*/
import "C"

/** @defgroup image_geometry_transforms Geometry Transforms
 *  @ingroup nppi
 *
 * Routines manipulating an image geometry.
 *
 * These functions can be found in the nppig library. Linking to only the sub-libraries that you use can significantly
 * save link time, application load time, and CUDA runtime startup time when using dynamic libraries.
 *
 * \section geometric_transform_api Geometric Transform API Specifics
 *
 * This section covers some of the unique API features common to the
 * geometric transform primitives.
 *
 * \subsection geometric_transform_roi Geometric Transforms and ROIs
 *
 * Geometric transforms operate on source and destination ROIs. The way
 * these ROIs affect the processing of pixels differs from other (non
 * geometric) image-processing primitives: Only pixels in the intersection
 * of the destination ROI and the transformed source ROI are being
 * processed.
 *
 * The typical processing proceedes as follows:
 * -# Transform the rectangular source ROI (given in source image coordinates)
 *		into the destination image space. This yields a quadrilateral.
 * -# Write only pixels in the intersection of the transformed source ROI and
 *		the destination ROI.
 *
 * \subsection geometric_transforms_interpolation Pixel Interpolation
 *
 * The majority of image geometry transform operation need to perform a
 * resampling of the source image as source and destination pixels are not
 * coincident.
 *
 * NPP supports the following pixel inerpolation modes (in order from fastest to
 * slowest and lowest to highest quality):
 * - nearest neighbor
 * - linear interpolation
 * - cubic convolution
 * - supersampling
 * - interpolation using Lanczos window function
 *
 * @{
 *
 */

/** @defgroup image_resize_square_pixel ResizeSqrPixel
 *
 * ResizeSqrPixel supports the following interpolation modes:
 *
 * \code
 *   NPPI_INTER_NN
 *   NPPI_INTER_LINEAR
 *   NPPI_INTER_CUBIC
 *   NPPI_INTER_CUBIC2P_BSPLINE
 *   NPPI_INTER_CUBIC2P_CATMULLROM
 *   NPPI_INTER_CUBIC2P_B05C03
 *   NPPI_INTER_SUPER
 *   NPPI_INTER_LANCZOS
 * \endcode
 *
 * ResizeSqrPixel attempts to choose source pixels that would approximately represent the center of the destination pixels.
 * It does so by using the following scaling formula to select source pixels for interpolation:
 *
 * \code
 *   nAdjustedXFactor = 1.0 / nXFactor;
 *   nAdjustedYFactor = 1.0 / nYFactor;
 *   nAdjustedXShift = nXShift * nAdjustedXFactor + ((1.0 - nAdjustedXFactor) * 0.5);
 *   nAdjustedYShift = nYShift * nAdjustedYFactor + ((1.0 - nAdjustedYFactor) * 0.5);
 *   nSrcX = nAdjustedXFactor * nDstX - nAdjustedXShift;
 *   nSrcY = nAdjustedYFactor * nDstY - nAdjustedYShift;
 * \endcode
 *
 * In the ResizeSqrPixel functions below source image clip checking is handled as follows:
 *
 * If the source pixel fractional x and y coordinates are greater than or equal to oSizeROI.x and less than oSizeROI.x + oSizeROI.width and
 * greater than or equal to oSizeROI.y and less than oSizeROI.y + oSizeROI.height then the source pixel is considered to be within
 * the source image clip rectangle and the source image is sampled.  Otherwise the source image is not sampled and a destination pixel is not
 * written to the destination image.
 *
 * \section resize_error_codes Error Codes
 * The resize primitives return the following error codes:
 *
 *         - ::NPP_WRONG_INTERSECTION_ROI_ERROR indicates an error condition if
 *           srcROIRect has no intersection with the source image.
 *         - ::NPP_RESIZE_NO_OPERATION_ERROR if either destination ROI width or
 *           height is less than 1 pixel.
 *         - ::NPP_RESIZE_FACTOR_ERROR Indicates an error condition if either nXFactor or
 *           nYFactor is less than or equal to zero or in the case of NPPI_INTER_SUPER are not both downscaling.
 *         - ::NPP_INTERPOLATION_ERROR if eInterpolation has an illegal value.
 *         - ::NPP_SIZE_ERROR if source size width or height is less than 2 pixels.
 *
 * @{
 *
 */

/** @name GetResizeRect
 * Returns NppiRect which represents the offset and size of the destination rectangle that would be generated by
 * resizing the source NppiRect by the requested scale factors and shifts.
 *
 * @{
 *
 */

/**
 * Data structure for variable ROI image resizing.
 *
 */

/**
 * General image descriptor. Defines the basic parameters of an image,
 * including data pointer, step size and size information.
 * This can be used by both source and destination sides.
 */
/*
  typedef struct
  {
	  const void * pSrc;  // device memory pointer
	  int nSrcStep;
	  void * pDst;         //device memory pointer
	  int nDstStep;
  } NppiResizeBatchCXR;

 typedef struct
 {
	 void *    pData;  // device memory pointer to the image
	 int 	  nStep;  // step size
	 NppiSize  oSize;  // width and height of the image
 } NppiImageDescriptor;

 typedef struct
 {
	 NppiRect oSrcRectROI;
	 NppiRect oDstRectROI;
 } NppiResizeBatchROI_Advanced;

 typedef struct
 {
	 const void * pSrc;  // device memory pointer, ignored for in place versions
	 int nSrcStep;
	 void * pDst;        // device memory pointer
	 int nDstStep;
 } NppiMirrorBatchCXR;

 typedef struct
 {
	 const void * pSrc;  //device memory pointer
	 int nSrcStep;
	 void * pDst;        //device memory pointer
	 int nDstStep;
	 Npp64f * pCoeffs;   // device memory pointer to the tranformation matrix with double precision floating-point coefficient values to be used for this image
	 Npp64f aTransformedCoeffs[3][3]; // FOR INTERNAL USE, DO NOT INITIALIZE
 } NppiWarpPerspectiveBatchCXR;


 typedef struct
 {
	 const void * pSrc;  // device memory pointer
	 int nSrcStep;
	 void * pDst;        // device memory pointer
	 int nDstStep;
	 Npp64f * pCoeffs;  //device memory pointer to the tranformation matrix with double precision floating-point coefficient values to be used for this image
	 Npp64f aTransformedCoeffs[2][3]; // FOR INTERNAL USE, DO NOT INITIALIZE
 } NppiWarpAffineBatchCXR;
*/
/*

 NppStatus nppiGetResizeRect(NppiRect oSrcROI, NppiRect *pDstRect, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst, int nDstStep, NppiRect oDstROI,double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_P3R(const Npp8u * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst[3], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_8u_P4R(const Npp8u * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst[4], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_P3R(const Npp16u * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst[3], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16u_P4R(const Npp16u * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16u * pDst[4], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_C1R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_C3R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_C4R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_AC4R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_P3R(const Npp16s * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst[3], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_16s_P4R(const Npp16s * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp16s * pDst[4], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_P3R(const Npp32f * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst[3], int nDstStep, NppiRect oDstROI,double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_32f_P4R(const Npp32f * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp32f * pDst[4], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_C1R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_C3R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_C4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_AC4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_P3R(const Npp64f * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst[3], int nDstStep, NppiRect oDstROI,double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeSqrPixel_64f_P4R(const Npp64f * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp64f * pDst[4], int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, double nXShift, double nYShift, int eInterpolation)
 NppStatus nppiResizeAdvancedGetBufferHostSize_8u_C1R(NppiSize oSrcROI, NppiSize oDstROI, int * hpBufferSize , int eInterpolationMode)
 NppStatus nppiResizeSqrPixel_8u_C1R_Advanced(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, Npp8u * pDst, int nDstStep, NppiRect oDstROI, double nXFactor, double nYFactor, Npp8u * pBuffer, int eInterpolationMode)
 NppStatus nppiGetResizeTiledSourceOffset(NppiRect oSrcRectROI, NppiRect oDstRectROI, NppiPoint * pNewSrcRectOffset)
 NppStatus nppiResize_8u_C1R(const Npp8u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_8u_C3R(const Npp8u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_8u_C4R(const Npp8u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_8u_AC4R(const Npp8u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_8u_P3R(const Npp8u * pSrc[3], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst[3], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_8u_P4R(const Npp8u * pSrc[4], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp8u * pDst[4], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_C1R(const Npp16u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_C3R(const Npp16u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_C4R(const Npp16u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_AC4R(const Npp16u * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_P3R(const Npp16u * pSrc[3], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst[3], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16u_P4R(const Npp16u * pSrc[4], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16u * pDst[4], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_C1R(const Npp16s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_C3R(const Npp16s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_C4R(const Npp16s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_AC4R(const Npp16s * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_P3R(const Npp16s * pSrc[3], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst[3], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_16s_P4R(const Npp16s * pSrc[4], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp16s * pDst[4], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_C1R(const Npp32f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp32f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_C3R(const Npp32f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp32f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_C4R(const Npp32f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp32f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_AC4R(const Npp32f * pSrc, int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI Npp32f * pDst, int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_P3R(const Npp32f * pSrc[3], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp32f * pDst[3], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResize_32f_P4R(const Npp32f * pSrc[4], int nSrcStep, NppiSize oSrcSize, NppiRect oSrcRectROI, Npp32f * pDst[4], int nDstStep, NppiSize oDstSize, NppiRect oDstRectROI, int eInterpolation)
 NppStatus nppiResizeBatch_8u_C1R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_8u_C3R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_8u_C4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_8u_AC4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_32f_C1R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_32f_C3R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_32f_C4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_32f_AC4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiSize oSmallestDstSize, NppiRect oDstRectROI, int eInterpolation, NppiResizeBatchCXR * pBatchList, unsigned int nBatchSize)
 NppStatus nppiResizeBatch_8u_C1R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_8u_C3R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_8u_C4R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_8u_AC4R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_32f_C1R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_32f_C3R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_32f_C4R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiResizeBatch_32f_AC4R_Advanced(int nMaxWidth, int nMaxHeight, NppiImageDescriptor * pBatchSrc, NppiImageDescriptor * pBatchDst, NppiResizeBatchROI_Advanced * pBatchROI, unsigned int nBatchSize, int eInterpolation)
 NppStatus nppiRemap_8u_C1R(const Npp8u  * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_8u_C3R(const Npp8u  * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_8u_C4R(const Npp8u  * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_8u_AC4R(const Npp8u  * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_8u_P3R(const Npp8u  * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst[3], int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_8u_P4R(const Npp8u  * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp8u  * pDst[4], int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_P3R(const Npp16u * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst[3], int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16u_P4R(const Npp16u * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16u * pDst[4], int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16s_C1R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep, Npp16s * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation)
 NppStatus nppiRemap_16s_C3R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp16s * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_16s_C4R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp16s * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_16s_AC4R(const Npp16s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					 const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						   Npp16s * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_16s_P3R(const Npp16s * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp16s * pDst[3], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_16s_P4R(const Npp16s * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp16s * pDst[4], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp32f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp32f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp32f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					 const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						   Npp32f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_P3R(const Npp32f * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp32f * pDst[3], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_32f_P4R(const Npp32f * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp32f * pXMap, int nXMapStep, const Npp32f * pYMap, int nYMapStep,
						  Npp32f * pDst[4], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_C1R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						  Npp64f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_C3R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						  Npp64f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_C4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						  Npp64f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_AC4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					 const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						   Npp64f * pDst, int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_P3R(const Npp64f * const pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						  Npp64f * pDst[3], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatus nppiRemap_64f_P4R(const Npp64f * const pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
					const Npp64f * pXMap, int nXMapStep, const Npp64f * pYMap, int nYMapStep,
						  Npp64f * pDst[4], int nDstStep, NppiSize oDstSizeROI, int eInterpolation);


 NppStatusnppiGetRotateQuad(NppiRect oSrcROI, double aQuad[4][2], double nAngle, double nShiftX, double nShiftY);


 NppStatus nppiGetRotateBound(NppiRect oSrcROI, double aBoundingBox[2][2], double nAngle, double nShiftX, double nShiftY);


 NppStatus nppiRotate_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
				   double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
				   double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
				   double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
					 double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
					double nAngle, double nShiftX, double nShiftY, int eInterpolation);


 NppStatus nppiRotate_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
						   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
					 double nAngle, double nShiftX, double nShiftY, int eInterpolation);

 NppStatus nppiMirror_8u_C1R(const Npp8u * pSrc, int nSrcStep,
						 Npp8u * pDst, int nDstStep,
				   NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_C1IR(Npp8u * pSrcDst, int nSrcDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_C3R(const Npp8u * pSrc, int nSrcStep,
						 Npp8u * pDst, int nDstStep,
				   NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_C3IR(Npp8u * pSrcDst, int nSrcDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_C4R(const Npp8u * pSrc, int nSrcStep,
						 Npp8u * pDst, int nDstStep,
				   NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_C4IR(Npp8u * pSrcDst, int nSrcDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_AC4R(const Npp8u * pSrc, int nSrcStep,
						  Npp8u * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_8u_AC4IR(Npp8u * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);

 NppStatus nppiMirror_16u_C1R(const Npp16u * pSrc, int nSrcStep,
						  Npp16u * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_C1IR(Npp16u * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_C3R(const Npp16u * pSrc, int nSrcStep,
						  Npp16u * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_C3IR(Npp16u * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_C4R(const Npp16u * pSrc, int nSrcStep,
						  Npp16u * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_C4IR(Npp16u * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16u_AC4R(const Npp16u * pSrc, int nSrcStep,
						   Npp16u * pDst, int nDstStep,
					 NppiSize oROI, NppiAxis flip);

 NppStatus nppiMirror_16u_AC4IR(Npp16u * pSrcDst, int nSrcDstStep,
					  NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C1R(const Npp16s * pSrc, int nSrcStep,
						  Npp16s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C1IR(Npp16s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C3R(const Npp16s * pSrc, int nSrcStep,
						  Npp16s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C3IR(Npp16s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C4R(const Npp16s * pSrc, int nSrcStep,
						  Npp16s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_C4IR(Npp16s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_AC4R(const Npp16s * pSrc, int nSrcStep,
						   Npp16s * pDst, int nDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_16s_AC4IR(Npp16s * pSrcDst, int nSrcDstStep,
					  NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C1R(const Npp32s * pSrc, int nSrcStep,
						  Npp32s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C1IR(Npp32s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C3R(const Npp32s * pSrc, int nSrcStep,
						  Npp32s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C3IR(Npp32s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C4R(const Npp32s * pSrc, int nSrcStep,
						  Npp32s * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_C4IR(Npp32s * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);



 NppStatus nppiMirror_32s_AC4R(const Npp32s * pSrc, int nSrcStep,
						   Npp32s * pDst, int nDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32s_AC4IR(Npp32s * pSrcDst, int nSrcDstStep,
					  NppiSize oROI, NppiAxis flip);



 NppStatus nppiMirror_32f_C1R(const Npp32f * pSrc, int nSrcStep,
						  Npp32f * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_C1IR(Npp32f * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);



 NppStatus nppiMirror_32f_C3R(const Npp32f * pSrc, int nSrcStep,
						  Npp32f * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_C3IR(Npp32f * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_C4R(const Npp32f * pSrc, int nSrcStep,
						  Npp32f * pDst, int nDstStep,
					NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_C4IR(Npp32f * pSrcDst, int nSrcDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_AC4R(const Npp32f * pSrc, int nSrcStep,
						   Npp32f * pDst, int nDstStep,
					 NppiSize oROI, NppiAxis flip);


 NppStatus nppiMirror_32f_AC4IR(Npp32f * pSrcDst, int nSrcDstStep,
					  NppiSize oROI, NppiAxis flip);



 NppStatus nppiMirrorBatch_32f_C1R(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_C1IR(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_C3R(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_C3IR(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_C4R(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_C4IR(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_AC4R(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiMirrorBatch_32f_AC4IR(NppiSize oSizeROI, NppiAxis flip, NppiMirrorBatchCXR * pBatchList, int nBatchSize);


 NppStatus nppiGetAffineTransform(NppiRect oSrcROI, const double aQuad[4][2], double aCoeffs[2][3]);



 NppStatus nppiGetAffineQuad(NppiRect oSrcROI, double aQuad[4][2], const double aCoeffs[2][3]);


 NppStatus nppiGetAffineBound(NppiRect oSrcROI, double aBound[2][2], const double aCoeffs[2][3]);


 NppStatus nppiWarpAffine_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
					   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
					   const double aCoeffs[2][3], int eInterpolation);



 NppStatus nppiWarpAffine_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
					   const double aCoeffs[2][3], int eInterpolation);



 NppStatus nppiWarpAffine_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);



 NppStatus nppiWarpAffine_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							 Npp8u * pDst[3], int nDstStep, NppiRect oDstROI,
					   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							 Npp8u * pDst[4], int nDstStep, NppiRect oDstROI,
					   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
						 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp16u * pDst[3], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp16u * pDst[4], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);

 NppStatus nppiWarpAffine_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
						 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32s * pDst[3], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32s * pDst[4], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
						 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32f * pDst[3], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp32f * pDst[4], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_C1R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp64f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_C3R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp64f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_C4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp64f * pDst, int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_AC4R(const Npp64f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							   Npp64f * pDst, int nDstStep, NppiRect oDstROI,
						 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_P3R(const Npp64f * aSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp64f * aDst[3], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffine_64f_P4R(const Npp64f * aSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
							  Npp64f * aDst[4], int nDstStep, NppiRect oDstROI,
						const double aCoeffs[2][3], int eInterpolation);





 NppStatus nppiWarpAffineBatchInit(NppiWarpAffineBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpAffineBatch_32f_C1R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpAffineBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpAffineBatch_32f_C3R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpAffineBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpAffineBatch_32f_C4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpAffineBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpAffineBatch_32f_AC4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							  int eInterpolation, NppiWarpAffineBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpAffineBack_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
						   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
						   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								 Npp8u * pDst, int nDstStep, NppiRect oDstROI,
						   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								 Npp8u * pDst[3], int nDstStep, NppiRect oDstROI,
						   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								 Npp8u * pDst[4], int nDstStep, NppiRect oDstROI,
						   const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp16u * pDst[3], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp16u * pDst[4], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32s * pDst[3], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);

 NppStatus nppiWarpAffineBack_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32s * pDst[4], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32f * pDst[3], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);


 NppStatus nppiWarpAffineBack_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp32f * pDst[4], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[2][3], int eInterpolation);



 NppStatus nppiWarpAffineQuad_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								 Npp8u * pDst,                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
						   int eInterpolation);



 NppStatus nppiWarpAffineQuad_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								 Npp8u * pDst,                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
						   int eInterpolation);


 NppStatus nppiWarpAffineQuad_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								 Npp8u * pDst,                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
						   int eInterpolation);


 NppStatus nppiWarpAffineQuad_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp8u * pDst,                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								 Npp8u * pDst[3],                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
						   int eInterpolation);


 NppStatus nppiWarpAffineQuad_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								 Npp8u * pDst[4],                    int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
						   int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI,                    const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								   Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							 int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp16u * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp16u * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								   Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							 int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32s * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32s * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								   Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							 int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32f * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);


 NppStatus nppiWarpAffineQuad_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
								  Npp32f * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2],
							int eInterpolation);



 NppStatus nppiGetPerspectiveTransform(NppiRect oSrcROI, const double quad[4][2], double aCoeffs[3][3]);



 NppStatus nppiGetPerspectiveQuad(NppiRect oSrcROI, double quad[4][2], const double aCoeffs[3][3]);


 NppStatus nppiGetPerspectiveBound(NppiRect oSrcROI, double bound[2][2], const double aCoeffs[3][3]);


 NppStatus nppiWarpPerspective_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
							const double aCoeffs[3][3], int eInterpolation);

 NppStatus nppiWarpPerspective_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp8u * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst[3], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[3][3], int eInterpolation);

 NppStatus nppiWarpPerspective_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								  Npp8u * pDst[4], int nDstStep, NppiRect oDstROI,
							const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3],int eInterpolation);


 NppStatus nppiWarpPerspective_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									Npp16u * pDst, int nDstStep, NppiRect oDstROI,
							  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst[3], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp16u * pDst[4], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);

 NppStatus nppiWarpPerspective_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									Npp32s * pDst, int nDstStep, NppiRect oDstROI,
							  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst[3], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32s * pDst[4], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									Npp32f * pDst, int nDstStep, NppiRect oDstROI,
							  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst[3], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspective_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
								   Npp32f * pDst[4], int nDstStep, NppiRect oDstROI,
							 const double aCoeffs[3][3], int eInterpolation);



 NppStatus nppiWarpPerspectiveBatchInit(NppiWarpPerspectiveBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpPerspectiveBatch_32f_C1R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpPerspectiveBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpPerspectiveBatch_32f_C3R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpPerspectiveBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpPerspectiveBatch_32f_C4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							 int eInterpolation, NppiWarpPerspectiveBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpPerspectiveBatch_32f_AC4R(NppiSize oSmallestSrcSize, NppiRect oSrcRectROI, NppiRect oDstRectROI,
							  int eInterpolation, NppiWarpPerspectiveBatchCXR * pBatchList, unsigned int nBatchSize);


 NppStatus nppiWarpPerspectiveBack_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
								const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
								const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI,
								const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp8u * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);

 NppStatus nppiWarpPerspectiveBack_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									  Npp8u * pDst[3], int nDstStep, NppiRect oDstROI,
								const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									  Npp8u * pDst[4], int nDstStep, NppiRect oDstROI,
								const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
										Npp16u * pDst, int nDstStep, NppiRect oDstROI,
								  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp16u * pDst[3], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp16u * pDst[4], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
										Npp32s * pDst, int nDstStep, NppiRect oDstROI,
								  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32s * pDst[3], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32s * pDst[4], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
										Npp32f * pDst, int nDstStep, NppiRect oDstROI,
								  const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32f * pDst[3], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


 NppStatus nppiWarpPerspectiveBack_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI,
									   Npp32f * pDst[4], int nDstStep, NppiRect oDstROI,
								 const double aCoeffs[3][3], int eInterpolation);


  NppStatus nppiWarpPerspectiveQuad_8u_C1R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_8u_C3R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI,  const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_8u_C4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									  Npp8u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_8u_AC4R(const Npp8u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp8u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_8u_P3R(const Npp8u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									  Npp8u * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_8u_P4R(const Npp8u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									  Npp8u * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_C1R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_C3R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_C4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_AC4R(const Npp16u * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
										Npp16u * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_P3R(const Npp16u * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp16u * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_16u_P4R(const Npp16u * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp16u * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_C1R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_C3R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_C4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_AC4R(const Npp32s * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
										Npp32s * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_P3R(const Npp32s * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32s * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32s_P4R(const Npp32s * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32s * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32f_C1R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32f_C3R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32f_C4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32f_AC4R(const Npp32f * pSrc, NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
										Npp32f * pDst, int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);

 NppStatus nppiWarpPerspectiveQuad_32f_P3R(const Npp32f * pSrc[3], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32f * pDst[3], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


 NppStatus nppiWarpPerspectiveQuad_32f_P4R(const Npp32f * pSrc[4], NppiSize oSrcSize, int nSrcStep, NppiRect oSrcROI, const double aSrcQuad[4][2],
									   Npp32f * pDst[4], int nDstStep, NppiRect oDstROI, const double aDstQuad[4][2], int eInterpolation);


*/
